// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomerActivities = `-- name: CountCustomerActivities :one
SELECT count(*) FROM customer_activities WHERE customer_id = $1
`

func (q *Queries) CountCustomerActivities(ctx context.Context, customerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomerActivities, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranchReview = `-- name: CreateBranchReview :one
INSERT INTO branch_reviews (booking_id, customer_id, branch_id, rating, comment, images)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, booking_id, customer_id, branch_id, rating, comment, images, created_at, updated_at
`

type CreateBranchReviewParams struct {
	BookingID  int64       `json:"booking_id"`
	CustomerID pgtype.Int8 `json:"customer_id"`
	BranchID   int64       `json:"branch_id"`
	Rating     int16       `json:"rating"`
	Comment    pgtype.Text `json:"comment"`
	Images     []byte      `json:"images"`
}

type CreateBranchReviewRow struct {
	ID         int64              `json:"id"`
	BookingID  int64              `json:"booking_id"`
	CustomerID pgtype.Int8        `json:"customer_id"`
	BranchID   int64              `json:"branch_id"`
	Rating     int16              `json:"rating"`
	Comment    pgtype.Text        `json:"comment"`
	Images     []byte             `json:"images"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateBranchReview(ctx context.Context, arg CreateBranchReviewParams) (CreateBranchReviewRow, error) {
	row := q.db.QueryRow(ctx, createBranchReview,
		arg.BookingID,
		arg.CustomerID,
		arg.BranchID,
		arg.Rating,
		arg.Comment,
		arg.Images,
	)
	var i CreateBranchReviewRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.CustomerID,
		&i.BranchID,
		&i.Rating,
		&i.Comment,
		&i.Images,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStaffReview = `-- name: CreateStaffReview :one
INSERT INTO staff_reviews (booking_id, customer_id, staff_id, rating, comment)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, booking_id, customer_id, staff_id, rating, comment, created_at, updated_at
`

type CreateStaffReviewParams struct {
	BookingID  int64       `json:"booking_id"`
	CustomerID pgtype.Int8 `json:"customer_id"`
	StaffID    int64       `json:"staff_id"`
	Rating     int16       `json:"rating"`
	Comment    pgtype.Text `json:"comment"`
}

type CreateStaffReviewRow struct {
	ID         int64              `json:"id"`
	BookingID  int64              `json:"booking_id"`
	CustomerID pgtype.Int8        `json:"customer_id"`
	StaffID    int64              `json:"staff_id"`
	Rating     int16              `json:"rating"`
	Comment    pgtype.Text        `json:"comment"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateStaffReview(ctx context.Context, arg CreateStaffReviewParams) (CreateStaffReviewRow, error) {
	row := q.db.QueryRow(ctx, createStaffReview,
		arg.BookingID,
		arg.CustomerID,
		arg.StaffID,
		arg.Rating,
		arg.Comment,
	)
	var i CreateStaffReviewRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.CustomerID,
		&i.StaffID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerProfileByUserID = `-- name: GetCustomerProfileByUserID :one
SELECT id, user_id, customer_code, phone_number, gender, date_of_birth, religion, allergies, avatar,
       address_line_1, address_line_2, city, state, country, status, created_at, updated_at
FROM customer_profiles WHERE user_id = $1
`

type GetCustomerProfileByUserIDRow struct {
	ID           int64              `json:"id"`
	UserID       pgtype.Int8        `json:"user_id"`
	CustomerCode pgtype.Text        `json:"customer_code"`
	PhoneNumber  pgtype.Text        `json:"phone_number"`
	Gender       pgtype.Text        `json:"gender"`
	DateOfBirth  pgtype.Date        `json:"date_of_birth"`
	Religion     pgtype.Text        `json:"religion"`
	Allergies    pgtype.Text        `json:"allergies"`
	Avatar       pgtype.Text        `json:"avatar"`
	AddressLine1 pgtype.Text        `json:"address_line_1"`
	AddressLine2 pgtype.Text        `json:"address_line_2"`
	City         pgtype.Text        `json:"city"`
	State        pgtype.Text        `json:"state"`
	Country      pgtype.Text        `json:"country"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerProfileByUserID(ctx context.Context, userID pgtype.Int8) (GetCustomerProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerProfileByUserID, userID)
	var i GetCustomerProfileByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustomerCode,
		&i.PhoneNumber,
		&i.Gender,
		&i.DateOfBirth,
		&i.Religion,
		&i.Allergies,
		&i.Avatar,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Country,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomerActivities = `-- name: ListCustomerActivities :many
SELECT id, customer_id, booking_id, created_at, updated_at FROM customer_activities
WHERE customer_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCustomerActivitiesParams struct {
	CustomerID int64 `json:"customer_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type ListCustomerActivitiesRow struct {
	ID         int64              `json:"id"`
	CustomerID int64              `json:"customer_id"`
	BookingID  pgtype.Int8        `json:"booking_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCustomerActivities(ctx context.Context, arg ListCustomerActivitiesParams) ([]ListCustomerActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listCustomerActivities, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerActivitiesRow{}
	for rows.Next() {
		var i ListCustomerActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.BookingID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCustomerProfile = `-- name: UpsertCustomerProfile :one
INSERT INTO customer_profiles (user_id, customer_code, phone_number, gender, date_of_birth, religion, allergies, avatar, address_line_1, address_line_2, city, state, country, status)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
ON CONFLICT (user_id) DO UPDATE SET
  phone_number = EXCLUDED.phone_number, gender = EXCLUDED.gender, date_of_birth = EXCLUDED.date_of_birth,
  religion = EXCLUDED.religion, allergies = EXCLUDED.allergies, avatar = EXCLUDED.avatar,
  address_line_1 = EXCLUDED.address_line_1, address_line_2 = EXCLUDED.address_line_2,
  city = EXCLUDED.city, state = EXCLUDED.state, country = EXCLUDED.country, status = EXCLUDED.status, updated_at = now()
RETURNING id, user_id, customer_code, phone_number, gender, date_of_birth, religion, allergies, avatar,
          address_line_1, address_line_2, city, state, country, status, created_at, updated_at
`

type UpsertCustomerProfileParams struct {
	UserID       pgtype.Int8 `json:"user_id"`
	CustomerCode pgtype.Text `json:"customer_code"`
	PhoneNumber  pgtype.Text `json:"phone_number"`
	Gender       pgtype.Text `json:"gender"`
	DateOfBirth  pgtype.Date `json:"date_of_birth"`
	Religion     pgtype.Text `json:"religion"`
	Allergies    pgtype.Text `json:"allergies"`
	Avatar       pgtype.Text `json:"avatar"`
	AddressLine1 pgtype.Text `json:"address_line_1"`
	AddressLine2 pgtype.Text `json:"address_line_2"`
	City         pgtype.Text `json:"city"`
	State        pgtype.Text `json:"state"`
	Country      pgtype.Text `json:"country"`
	Status       string      `json:"status"`
}

type UpsertCustomerProfileRow struct {
	ID           int64              `json:"id"`
	UserID       pgtype.Int8        `json:"user_id"`
	CustomerCode pgtype.Text        `json:"customer_code"`
	PhoneNumber  pgtype.Text        `json:"phone_number"`
	Gender       pgtype.Text        `json:"gender"`
	DateOfBirth  pgtype.Date        `json:"date_of_birth"`
	Religion     pgtype.Text        `json:"religion"`
	Allergies    pgtype.Text        `json:"allergies"`
	Avatar       pgtype.Text        `json:"avatar"`
	AddressLine1 pgtype.Text        `json:"address_line_1"`
	AddressLine2 pgtype.Text        `json:"address_line_2"`
	City         pgtype.Text        `json:"city"`
	State        pgtype.Text        `json:"state"`
	Country      pgtype.Text        `json:"country"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertCustomerProfile(ctx context.Context, arg UpsertCustomerProfileParams) (UpsertCustomerProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertCustomerProfile,
		arg.UserID,
		arg.CustomerCode,
		arg.PhoneNumber,
		arg.Gender,
		arg.DateOfBirth,
		arg.Religion,
		arg.Allergies,
		arg.Avatar,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.Country,
		arg.Status,
	)
	var i UpsertCustomerProfileRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustomerCode,
		&i.PhoneNumber,
		&i.Gender,
		&i.DateOfBirth,
		&i.Religion,
		&i.Allergies,
		&i.Avatar,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Country,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
