// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BranchReview struct {
	ID         int64              `json:"id"`
	BookingID  int64              `json:"booking_id"`
	CustomerID pgtype.Int8        `json:"customer_id"`
	BranchID   int64              `json:"branch_id"`
	Rating     int16              `json:"rating"`
	Comment    pgtype.Text        `json:"comment"`
	Images     []byte             `json:"images"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ProviderID pgtype.Int8        `json:"provider_id"`
}

type CustomerActivity struct {
	ID                   int64              `json:"id"`
	CustomerID           int64              `json:"customer_id"`
	BookingID            pgtype.Int8        `json:"booking_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ProviderID           pgtype.Int8        `json:"provider_id"`
	BranchID             pgtype.Int8        `json:"branch_id"`
	BookingDate          pgtype.Date        `json:"booking_date"`
	Status               pgtype.Text        `json:"status"`
	TotalPriceMinorUnits int64              `json:"total_price_minor_units"`
	Currency             string             `json:"currency"`
}

type CustomerProfile struct {
	ID           int64              `json:"id"`
	UserID       pgtype.Int8        `json:"user_id"`
	CustomerCode pgtype.Text        `json:"customer_code"`
	PhoneNumber  pgtype.Text        `json:"phone_number"`
	Gender       pgtype.Text        `json:"gender"`
	DateOfBirth  pgtype.Date        `json:"date_of_birth"`
	Religion     pgtype.Text        `json:"religion"`
	Allergies    pgtype.Text        `json:"allergies"`
	Avatar       pgtype.Text        `json:"avatar"`
	AddressLine1 pgtype.Text        `json:"address_line_1"`
	AddressLine2 pgtype.Text        `json:"address_line_2"`
	City         pgtype.Text        `json:"city"`
	State        pgtype.Text        `json:"state"`
	Country      pgtype.Text        `json:"country"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DisplayName  pgtype.Text        `json:"display_name"`
	Email        pgtype.Text        `json:"email"`
}

type InboxEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Topic       string             `json:"topic"`
	PartitionID int32              `json:"partition_id"`
	OffsetID    int64              `json:"offset_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.UUID        `json:"locked_by"`
}

type PendingCustomerActivity struct {
	BookingID            int64              `json:"booking_id"`
	UserID               int64              `json:"user_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ProviderID           pgtype.Int8        `json:"provider_id"`
	BranchID             pgtype.Int8        `json:"branch_id"`
	BookingDate          pgtype.Date        `json:"booking_date"`
	Status               pgtype.Text        `json:"status"`
	TotalPriceMinorUnits int64              `json:"total_price_minor_units"`
	Currency             string             `json:"currency"`
}

type StaffReview struct {
	ID         int64              `json:"id"`
	BookingID  int64              `json:"booking_id"`
	CustomerID pgtype.Int8        `json:"customer_id"`
	StaffID    int64              `json:"staff_id"`
	Rating     int16              `json:"rating"`
	Comment    pgtype.Text        `json:"comment"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ProviderID pgtype.Int8        `json:"provider_id"`
	BranchID   pgtype.Int8        `json:"branch_id"`
}
