-- +goose Up
CREATE TABLE chat_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    provider_user_id BIGINT,
    branch_user_id BIGINT,
    customer_user_id BIGINT,
    conversation_type VARCHAR(40) NOT NULL DEFAULT 'provider_admin',
    last_message_id BIGINT,
    last_message_at TIMESTAMPTZ,
    last_admin_read_at TIMESTAMPTZ,
    last_provider_read_at TIMESTAMPTZ,
    last_branch_read_at TIMESTAMPTZ,
    last_customer_read_at TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    ticket_status VARCHAR(30) NOT NULL DEFAULT 'none',
    ticket_subject VARCHAR(160),
    ticket_body TEXT,
    ticket_rejection_reason TEXT,
    ticket_requested_at TIMESTAMPTZ,
    ticket_reviewed_at TIMESTAMPTZ,
    ticket_reviewed_by BIGINT,
    opened_by_user_id BIGINT,
    closed_by_user_id BIGINT,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX chat_threads_provider_last_idx ON chat_threads(provider_id, last_message_at DESC);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_thread_id BIGINT NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
    sender_id BIGINT,
    sender_role VARCHAR(30) NOT NULL,
    body TEXT NOT NULL,
    attachment_object_id UUID,
    attachment_name TEXT,
    attachment_mime VARCHAR(120),
    attachment_size INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX chat_messages_thread_time_idx ON chat_messages(chat_thread_id, created_at);

CREATE TABLE inbox_events (
    event_id UUID PRIMARY KEY, topic TEXT NOT NULL, partition_id INTEGER NOT NULL,
    offset_id BIGINT NOT NULL, event_type TEXT NOT NULL, processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(topic, partition_id, offset_id)
);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL,
    event_type TEXT NOT NULL, event_version INTEGER NOT NULL, payload BYTEA NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ, attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX chat_outbox_unpublished_idx ON outbox_events(occurred_at) WHERE published_at IS NULL;

-- +goose Down
DROP TABLE IF EXISTS outbox_events, inbox_events, chat_messages, chat_threads CASCADE;

