// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InboxEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Topic       string             `json:"topic"`
	PartitionID int32              `json:"partition_id"`
	OffsetID    int64              `json:"offset_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.UUID        `json:"locked_by"`
}

type ProviderBranch struct {
	ID               int64              `json:"id"`
	ProviderID       int64              `json:"provider_id"`
	BranchName       string             `json:"branch_name"`
	Email            pgtype.Text        `json:"email"`
	PhoneCode        string             `json:"phone_code"`
	PhoneNumber      pgtype.Text        `json:"phone_number"`
	Address          pgtype.Text        `json:"address"`
	CountryID        pgtype.Text        `json:"country_id"`
	StateID          pgtype.Text        `json:"state_id"`
	CityID           pgtype.Text        `json:"city_id"`
	Latitude         pgtype.Numeric     `json:"latitude"`
	Longitude        pgtype.Numeric     `json:"longitude"`
	ZipCode          pgtype.Text        `json:"zip_code"`
	WorkingStartHour pgtype.Time        `json:"working_start_hour"`
	WorkingEndHour   pgtype.Time        `json:"working_end_hour"`
	WorkingDays      []byte             `json:"working_days"`
	Holidays         []byte             `json:"holidays"`
	ImageObjectID    pgtype.UUID        `json:"image_object_id"`
	ImageObjectIds   []byte             `json:"image_object_ids"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ProviderProfile struct {
	ID                    int64              `json:"id"`
	UserID                pgtype.Int8        `json:"user_id"`
	Image                 pgtype.Text        `json:"image"`
	PhoneNumber           pgtype.Text        `json:"phone_number"`
	Category              pgtype.Text        `json:"category"`
	Status                string             `json:"status"`
	OnboardingStatus      string             `json:"onboarding_status"`
	OnboardingCurrentStep pgtype.Text        `json:"onboarding_current_step"`
	OnboardingVersion     int32              `json:"onboarding_version"`
	TrialStartsAt         pgtype.Timestamptz `json:"trial_starts_at"`
	TrialEndsAt           pgtype.Timestamptz `json:"trial_ends_at"`
	DocumentStatus        string             `json:"document_status"`
	KtpObjectID           pgtype.UUID        `json:"ktp_object_id"`
	NibNumber             pgtype.Text        `json:"nib_number"`
	NibObjectID           pgtype.UUID        `json:"nib_object_id"`
	BusinessObjectID      pgtype.UUID        `json:"business_object_id"`
	DocumentNote          pgtype.Text        `json:"document_note"`
	DocumentSubmittedAt   pgtype.Timestamptz `json:"document_submitted_at"`
	DocumentVerifiedAt    pgtype.Timestamptz `json:"document_verified_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DisplayName           string             `json:"display_name"`
}

type ProviderRole struct {
	ID             int64              `json:"id"`
	ProviderID     int64              `json:"provider_id"`
	BranchID       pgtype.Int8        `json:"branch_id"`
	RoleName       string             `json:"role_name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IdentityUserID pgtype.Int8        `json:"identity_user_id"`
}

type ProviderRoleMenuPermission struct {
	ID             int64  `json:"id"`
	ProviderRoleID int64  `json:"provider_role_id"`
	MenuKey        string `json:"menu_key"`
}

type ProviderStaff struct {
	ID             int64              `json:"id"`
	ProviderID     int64              `json:"provider_id"`
	BranchID       pgtype.Int8        `json:"branch_id"`
	ProviderRoleID pgtype.Int8        `json:"provider_role_id"`
	ImageObjectID  pgtype.UUID        `json:"image_object_id"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Email          string             `json:"email"`
	Username       pgtype.Text        `json:"username"`
	CountryCode    pgtype.Text        `json:"country_code"`
	PhoneNumber    pgtype.Text        `json:"phone_number"`
	Gender         pgtype.Text        `json:"gender"`
	DateOfBirth    pgtype.Date        `json:"date_of_birth"`
	Address        pgtype.Text        `json:"address"`
	CountryID      pgtype.Text        `json:"country_id"`
	StateID        pgtype.Text        `json:"state_id"`
	CityID         pgtype.Text        `json:"city_id"`
	PostalCode     pgtype.Text        `json:"postal_code"`
	Bio            pgtype.Text        `json:"bio"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Role           string             `json:"role"`
	Rating         pgtype.Numeric     `json:"rating"`
	CurrentStatus  string             `json:"current_status"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type StaffSchedule struct {
	ID          int64              `json:"id"`
	StaffID     int64              `json:"staff_id"`
	DayOfWeek   string             `json:"day_of_week"`
	StartTime   pgtype.Time        `json:"start_time"`
	EndTime     pgtype.Time        `json:"end_time"`
	IsAvailable bool               `json:"is_available"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type StaffSkill struct {
	ID        int64              `json:"id"`
	StaffID   int64              `json:"staff_id"`
	ServiceID int64              `json:"service_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
