// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderBranch = `-- name: CreateProviderBranch :one
INSERT INTO provider_branches (provider_id, branch_name, email, phone_code, phone_number, address, country_id, state_id, city_id, latitude, longitude, zip_code, working_start_hour, working_end_hour, working_days, holidays, image_object_id, image_object_ids, status, description, branch_type, timezone, opened_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23)
RETURNING id, provider_id, branch_name, email, phone_code, phone_number, address, country_id, state_id, city_id,
          latitude, longitude, zip_code, working_start_hour, working_end_hour, working_days, holidays,
          image_object_id, image_object_ids, status, created_at, updated_at, description, branch_type, timezone, opened_at
`

type CreateProviderBranchParams struct {
	ProviderID       int64          `json:"provider_id"`
	BranchName       string         `json:"branch_name"`
	Email            pgtype.Text    `json:"email"`
	PhoneCode        string         `json:"phone_code"`
	PhoneNumber      pgtype.Text    `json:"phone_number"`
	Address          pgtype.Text    `json:"address"`
	CountryID        pgtype.Text    `json:"country_id"`
	StateID          pgtype.Text    `json:"state_id"`
	CityID           pgtype.Text    `json:"city_id"`
	Latitude         pgtype.Numeric `json:"latitude"`
	Longitude        pgtype.Numeric `json:"longitude"`
	ZipCode          pgtype.Text    `json:"zip_code"`
	WorkingStartHour pgtype.Time    `json:"working_start_hour"`
	WorkingEndHour   pgtype.Time    `json:"working_end_hour"`
	WorkingDays      []byte         `json:"working_days"`
	Holidays         []byte         `json:"holidays"`
	ImageObjectID    pgtype.UUID    `json:"image_object_id"`
	ImageObjectIds   []byte         `json:"image_object_ids"`
	Status           string         `json:"status"`
	Description      string         `json:"description"`
	BranchType       string         `json:"branch_type"`
	Timezone         string         `json:"timezone"`
	OpenedAt         pgtype.Date    `json:"opened_at"`
}

func (q *Queries) CreateProviderBranch(ctx context.Context, arg CreateProviderBranchParams) (ProviderBranch, error) {
	row := q.db.QueryRow(ctx, createProviderBranch,
		arg.ProviderID,
		arg.BranchName,
		arg.Email,
		arg.PhoneCode,
		arg.PhoneNumber,
		arg.Address,
		arg.CountryID,
		arg.StateID,
		arg.CityID,
		arg.Latitude,
		arg.Longitude,
		arg.ZipCode,
		arg.WorkingStartHour,
		arg.WorkingEndHour,
		arg.WorkingDays,
		arg.Holidays,
		arg.ImageObjectID,
		arg.ImageObjectIds,
		arg.Status,
		arg.Description,
		arg.BranchType,
		arg.Timezone,
		arg.OpenedAt,
	)
	var i ProviderBranch
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BranchName,
		&i.Email,
		&i.PhoneCode,
		&i.PhoneNumber,
		&i.Address,
		&i.CountryID,
		&i.StateID,
		&i.CityID,
		&i.Latitude,
		&i.Longitude,
		&i.ZipCode,
		&i.WorkingStartHour,
		&i.WorkingEndHour,
		&i.WorkingDays,
		&i.Holidays,
		&i.ImageObjectID,
		&i.ImageObjectIds,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.BranchType,
		&i.Timezone,
		&i.OpenedAt,
	)
	return i, err
}

const getBranchInProviderScope = `-- name: GetBranchInProviderScope :one
SELECT id, provider_id, branch_name, email, phone_code, phone_number, address, country_id, state_id, city_id,
       latitude, longitude, zip_code, working_start_hour, working_end_hour, working_days, holidays,
       image_object_id, image_object_ids, status, created_at, updated_at, description, branch_type, timezone, opened_at
FROM provider_branches WHERE id = $1 AND provider_id = $2
`

type GetBranchInProviderScopeParams struct {
	ID         int64 `json:"id"`
	ProviderID int64 `json:"provider_id"`
}

func (q *Queries) GetBranchInProviderScope(ctx context.Context, arg GetBranchInProviderScopeParams) (ProviderBranch, error) {
	row := q.db.QueryRow(ctx, getBranchInProviderScope, arg.ID, arg.ProviderID)
	var i ProviderBranch
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BranchName,
		&i.Email,
		&i.PhoneCode,
		&i.PhoneNumber,
		&i.Address,
		&i.CountryID,
		&i.StateID,
		&i.CityID,
		&i.Latitude,
		&i.Longitude,
		&i.ZipCode,
		&i.WorkingStartHour,
		&i.WorkingEndHour,
		&i.WorkingDays,
		&i.Holidays,
		&i.ImageObjectID,
		&i.ImageObjectIds,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.BranchType,
		&i.Timezone,
		&i.OpenedAt,
	)
	return i, err
}

const getBranchRoleName = `-- name: GetBranchRoleName :one
SELECT role_name FROM provider_roles
WHERE provider_id = $1 AND identity_user_id = $2 AND status = 'active'
ORDER BY id LIMIT 1
`

type GetBranchRoleNameParams struct {
	ProviderID     int64       `json:"provider_id"`
	IdentityUserID pgtype.Int8 `json:"identity_user_id"`
}

func (q *Queries) GetBranchRoleName(ctx context.Context, arg GetBranchRoleNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getBranchRoleName, arg.ProviderID, arg.IdentityUserID)
	var role_name string
	err := row.Scan(&role_name)
	return role_name, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, user_id, image, phone_number, category, status, onboarding_status, onboarding_current_step,
       onboarding_version, trial_starts_at, trial_ends_at, document_status, ktp_object_id, nib_number,
       nib_object_id, business_object_id, document_note, document_submitted_at, document_verified_at, created_at, updated_at
FROM provider_profiles WHERE id = $1
`

type GetProviderByIDRow struct {
	ID                    int64              `json:"id"`
	UserID                pgtype.Int8        `json:"user_id"`
	Image                 pgtype.Text        `json:"image"`
	PhoneNumber           pgtype.Text        `json:"phone_number"`
	Category              pgtype.Text        `json:"category"`
	Status                string             `json:"status"`
	OnboardingStatus      string             `json:"onboarding_status"`
	OnboardingCurrentStep pgtype.Text        `json:"onboarding_current_step"`
	OnboardingVersion     int32              `json:"onboarding_version"`
	TrialStartsAt         pgtype.Timestamptz `json:"trial_starts_at"`
	TrialEndsAt           pgtype.Timestamptz `json:"trial_ends_at"`
	DocumentStatus        string             `json:"document_status"`
	KtpObjectID           pgtype.UUID        `json:"ktp_object_id"`
	NibNumber             pgtype.Text        `json:"nib_number"`
	NibObjectID           pgtype.UUID        `json:"nib_object_id"`
	BusinessObjectID      pgtype.UUID        `json:"business_object_id"`
	DocumentNote          pgtype.Text        `json:"document_note"`
	DocumentSubmittedAt   pgtype.Timestamptz `json:"document_submitted_at"`
	DocumentVerifiedAt    pgtype.Timestamptz `json:"document_verified_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProviderByID(ctx context.Context, id int64) (GetProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i GetProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Image,
		&i.PhoneNumber,
		&i.Category,
		&i.Status,
		&i.OnboardingStatus,
		&i.OnboardingCurrentStep,
		&i.OnboardingVersion,
		&i.TrialStartsAt,
		&i.TrialEndsAt,
		&i.DocumentStatus,
		&i.KtpObjectID,
		&i.NibNumber,
		&i.NibObjectID,
		&i.BusinessObjectID,
		&i.DocumentNote,
		&i.DocumentSubmittedAt,
		&i.DocumentVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.menu_key FROM provider_role_menu_permissions p WHERE p.provider_role_id = $1 ORDER BY p.menu_key LIMIT 500
`

func (q *Queries) GetRolePermissions(ctx context.Context, providerRoleID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, providerRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var menu_key string
		if err := rows.Scan(&menu_key); err != nil {
			return nil, err
		}
		items = append(items, menu_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleStaff = `-- name: ListEligibleStaff :many
SELECT DISTINCT s.id, s.provider_id, s.branch_id, s.provider_role_id, s.image_object_id, s.first_name, s.last_name,
       s.email, s.username, s.country_code, s.phone_number, s.gender, s.date_of_birth, s.address, s.country_id,
       s.state_id, s.city_id, s.postal_code, s.bio, s.category_id, s.role, s.rating, s.current_status, s.status,
       s.created_at, s.updated_at
FROM provider_staffs s
JOIN staff_skills sk ON sk.staff_id = s.id
WHERE s.provider_id = $1 AND s.branch_id = $2 AND s.status = 'active' AND s.current_status <> 'offline'
  AND sk.service_id = ANY($3::bigint[])
ORDER BY s.id LIMIT 500
`

type ListEligibleStaffParams struct {
	ProviderID int64       `json:"provider_id"`
	BranchID   pgtype.Int8 `json:"branch_id"`
	Column3    []int64     `json:"column_3"`
}

func (q *Queries) ListEligibleStaff(ctx context.Context, arg ListEligibleStaffParams) ([]ProviderStaff, error) {
	rows, err := q.db.Query(ctx, listEligibleStaff, arg.ProviderID, arg.BranchID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderStaff{}
	for rows.Next() {
		var i ProviderStaff
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.BranchID,
			&i.ProviderRoleID,
			&i.ImageObjectID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Username,
			&i.CountryCode,
			&i.PhoneNumber,
			&i.Gender,
			&i.DateOfBirth,
			&i.Address,
			&i.CountryID,
			&i.StateID,
			&i.CityID,
			&i.PostalCode,
			&i.Bio,
			&i.CategoryID,
			&i.Role,
			&i.Rating,
			&i.CurrentStatus,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderBranches = `-- name: ListProviderBranches :many
SELECT id, provider_id, branch_name, email, phone_code, phone_number, address, country_id, state_id, city_id,
       latitude, longitude, zip_code, working_start_hour, working_end_hour, working_days, holidays,
       image_object_id, image_object_ids, status, created_at, updated_at, description, branch_type, timezone, opened_at
FROM provider_branches WHERE provider_id = $1 ORDER BY id LIMIT $2 OFFSET $3
`

type ListProviderBranchesParams struct {
	ProviderID int64 `json:"provider_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListProviderBranches(ctx context.Context, arg ListProviderBranchesParams) ([]ProviderBranch, error) {
	rows, err := q.db.Query(ctx, listProviderBranches, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderBranch{}
	for rows.Next() {
		var i ProviderBranch
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.BranchName,
			&i.Email,
			&i.PhoneCode,
			&i.PhoneNumber,
			&i.Address,
			&i.CountryID,
			&i.StateID,
			&i.CityID,
			&i.Latitude,
			&i.Longitude,
			&i.ZipCode,
			&i.WorkingStartHour,
			&i.WorkingEndHour,
			&i.WorkingDays,
			&i.Holidays,
			&i.ImageObjectID,
			&i.ImageObjectIds,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.BranchType,
			&i.Timezone,
			&i.OpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOnboarding = `-- name: UpdateOnboarding :one
UPDATE provider_profiles SET onboarding_status = $2, onboarding_current_step = $3,
  onboarding_version = $4, updated_at = now() WHERE id = $1
RETURNING id, user_id, image, phone_number, category, status, onboarding_status, onboarding_current_step,
          onboarding_version, trial_starts_at, trial_ends_at, document_status, ktp_object_id, nib_number,
          nib_object_id, business_object_id, document_note, document_submitted_at, document_verified_at, created_at, updated_at
`

type UpdateOnboardingParams struct {
	ID                    int64       `json:"id"`
	OnboardingStatus      string      `json:"onboarding_status"`
	OnboardingCurrentStep pgtype.Text `json:"onboarding_current_step"`
	OnboardingVersion     int32       `json:"onboarding_version"`
}

type UpdateOnboardingRow struct {
	ID                    int64              `json:"id"`
	UserID                pgtype.Int8        `json:"user_id"`
	Image                 pgtype.Text        `json:"image"`
	PhoneNumber           pgtype.Text        `json:"phone_number"`
	Category              pgtype.Text        `json:"category"`
	Status                string             `json:"status"`
	OnboardingStatus      string             `json:"onboarding_status"`
	OnboardingCurrentStep pgtype.Text        `json:"onboarding_current_step"`
	OnboardingVersion     int32              `json:"onboarding_version"`
	TrialStartsAt         pgtype.Timestamptz `json:"trial_starts_at"`
	TrialEndsAt           pgtype.Timestamptz `json:"trial_ends_at"`
	DocumentStatus        string             `json:"document_status"`
	KtpObjectID           pgtype.UUID        `json:"ktp_object_id"`
	NibNumber             pgtype.Text        `json:"nib_number"`
	NibObjectID           pgtype.UUID        `json:"nib_object_id"`
	BusinessObjectID      pgtype.UUID        `json:"business_object_id"`
	DocumentNote          pgtype.Text        `json:"document_note"`
	DocumentSubmittedAt   pgtype.Timestamptz `json:"document_submitted_at"`
	DocumentVerifiedAt    pgtype.Timestamptz `json:"document_verified_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOnboarding(ctx context.Context, arg UpdateOnboardingParams) (UpdateOnboardingRow, error) {
	row := q.db.QueryRow(ctx, updateOnboarding,
		arg.ID,
		arg.OnboardingStatus,
		arg.OnboardingCurrentStep,
		arg.OnboardingVersion,
	)
	var i UpdateOnboardingRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Image,
		&i.PhoneNumber,
		&i.Category,
		&i.Status,
		&i.OnboardingStatus,
		&i.OnboardingCurrentStep,
		&i.OnboardingVersion,
		&i.TrialStartsAt,
		&i.TrialEndsAt,
		&i.DocumentStatus,
		&i.KtpObjectID,
		&i.NibNumber,
		&i.NibObjectID,
		&i.BusinessObjectID,
		&i.DocumentNote,
		&i.DocumentSubmittedAt,
		&i.DocumentVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
