-- +goose Up
CREATE TABLE customer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    customer_code VARCHAR(32) UNIQUE,
    phone_number TEXT,
    gender TEXT,
    date_of_birth DATE,
    religion TEXT,
    allergies TEXT,
    avatar TEXT,
    address_line_1 TEXT,
    address_line_2 TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE customer_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer_profiles(id) ON DELETE CASCADE,
    booking_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX customer_activities_customer_time_idx ON customer_activities(customer_id, created_at DESC);

CREATE TABLE branch_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE,
    customer_id BIGINT REFERENCES customer_profiles(id) ON DELETE SET NULL,
    branch_id BIGINT NOT NULL,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    images JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX branch_reviews_branch_time_idx ON branch_reviews(branch_id, created_at DESC);

CREATE TABLE staff_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    customer_id BIGINT REFERENCES customer_profiles(id) ON DELETE SET NULL,
    staff_id BIGINT NOT NULL,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (booking_id, staff_id)
);
CREATE INDEX staff_reviews_staff_time_idx ON staff_reviews(staff_id, created_at DESC);

CREATE TABLE inbox_events (
    event_id UUID PRIMARY KEY,
    topic TEXT NOT NULL,
    partition_id INTEGER NOT NULL,
    offset_id BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(topic, partition_id, offset_id)
);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL,
    event_type TEXT NOT NULL, event_version INTEGER NOT NULL, payload BYTEA NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ, attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX customer_outbox_unpublished_idx ON outbox_events(occurred_at) WHERE published_at IS NULL;

-- +goose Down
DROP TABLE IF EXISTS outbox_events, inbox_events, staff_reviews, branch_reviews, customer_activities, customer_profiles CASCADE;

