// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (booking_code, provider_id, customer_id, branch_id, staff_id, booking_type, booking_date, status, starts_at, ends_at,
  total_duration, total_price, currency, customer_name, customer_phone, participant_count, notes, queue_number,
  held_at, hold_expires_at, idempotency_key)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)
RETURNING id, booking_code, provider_id, customer_id, branch_id, staff_id, booking_type, booking_date, status, starts_at, ends_at,
  actual_started_at, actual_ended_at, total_duration, total_price, currency, customer_name, customer_phone,
  participant_count, notes, queue_number, checked_in_at, completed_at, held_at, hold_expires_at, expired_at,
  idempotency_key, created_at, updated_at
`

type CreateBookingParams struct {
	BookingCode      string             `json:"booking_code"`
	ProviderID       int64              `json:"provider_id"`
	CustomerID       pgtype.Int8        `json:"customer_id"`
	BranchID         pgtype.Int8        `json:"branch_id"`
	StaffID          pgtype.Int8        `json:"staff_id"`
	BookingType      string             `json:"booking_type"`
	BookingDate      pgtype.Date        `json:"booking_date"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	TotalDuration    int32              `json:"total_duration"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	Currency         string             `json:"currency"`
	CustomerName     pgtype.Text        `json:"customer_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	ParticipantCount int16              `json:"participant_count"`
	Notes            pgtype.Text        `json:"notes"`
	QueueNumber      pgtype.Int4        `json:"queue_number"`
	HeldAt           pgtype.Timestamptz `json:"held_at"`
	HoldExpiresAt    pgtype.Timestamptz `json:"hold_expires_at"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
}

type CreateBookingRow struct {
	ID               int64              `json:"id"`
	BookingCode      string             `json:"booking_code"`
	ProviderID       int64              `json:"provider_id"`
	CustomerID       pgtype.Int8        `json:"customer_id"`
	BranchID         pgtype.Int8        `json:"branch_id"`
	StaffID          pgtype.Int8        `json:"staff_id"`
	BookingType      string             `json:"booking_type"`
	BookingDate      pgtype.Date        `json:"booking_date"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	ActualStartedAt  pgtype.Timestamptz `json:"actual_started_at"`
	ActualEndedAt    pgtype.Timestamptz `json:"actual_ended_at"`
	TotalDuration    int32              `json:"total_duration"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	Currency         string             `json:"currency"`
	CustomerName     pgtype.Text        `json:"customer_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	ParticipantCount int16              `json:"participant_count"`
	Notes            pgtype.Text        `json:"notes"`
	QueueNumber      pgtype.Int4        `json:"queue_number"`
	CheckedInAt      pgtype.Timestamptz `json:"checked_in_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	HeldAt           pgtype.Timestamptz `json:"held_at"`
	HoldExpiresAt    pgtype.Timestamptz `json:"hold_expires_at"`
	ExpiredAt        pgtype.Timestamptz `json:"expired_at"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.BookingCode,
		arg.ProviderID,
		arg.CustomerID,
		arg.BranchID,
		arg.StaffID,
		arg.BookingType,
		arg.BookingDate,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
		arg.TotalDuration,
		arg.TotalPrice,
		arg.Currency,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.ParticipantCount,
		arg.Notes,
		arg.QueueNumber,
		arg.HeldAt,
		arg.HoldExpiresAt,
		arg.IdempotencyKey,
	)
	var i CreateBookingRow
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.ProviderID,
		&i.CustomerID,
		&i.BranchID,
		&i.StaffID,
		&i.BookingType,
		&i.BookingDate,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.ActualStartedAt,
		&i.ActualEndedAt,
		&i.TotalDuration,
		&i.TotalPrice,
		&i.Currency,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ParticipantCount,
		&i.Notes,
		&i.QueueNumber,
		&i.CheckedInAt,
		&i.CompletedAt,
		&i.HeldAt,
		&i.HoldExpiresAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookingParticipant = `-- name: CreateBookingParticipant :one
INSERT INTO booking_participants (booking_id, position, is_primary, name, phone, email, gender, age_group, description,
  provider_staff_id, starts_at, ends_at, total_duration, total_price)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id
`

type CreateBookingParticipantParams struct {
	BookingID       int64              `json:"booking_id"`
	Position        int16              `json:"position"`
	IsPrimary       bool               `json:"is_primary"`
	Name            string             `json:"name"`
	Phone           pgtype.Text        `json:"phone"`
	Email           pgtype.Text        `json:"email"`
	Gender          pgtype.Text        `json:"gender"`
	AgeGroup        pgtype.Text        `json:"age_group"`
	Description     pgtype.Text        `json:"description"`
	ProviderStaffID pgtype.Int8        `json:"provider_staff_id"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	TotalDuration   int32              `json:"total_duration"`
	TotalPrice      pgtype.Numeric     `json:"total_price"`
}

func (q *Queries) CreateBookingParticipant(ctx context.Context, arg CreateBookingParticipantParams) (int64, error) {
	row := q.db.QueryRow(ctx, createBookingParticipant,
		arg.BookingID,
		arg.Position,
		arg.IsPrimary,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Gender,
		arg.AgeGroup,
		arg.Description,
		arg.ProviderStaffID,
		arg.StartsAt,
		arg.EndsAt,
		arg.TotalDuration,
		arg.TotalPrice,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createBookingServiceSnapshot = `-- name: CreateBookingServiceSnapshot :exec
INSERT INTO booking_services (booking_id, service_id, service_title, price, estimated_duration)
VALUES ($1,$2,$3,$4,$5)
`

type CreateBookingServiceSnapshotParams struct {
	BookingID         int64          `json:"booking_id"`
	ServiceID         int64          `json:"service_id"`
	ServiceTitle      string         `json:"service_title"`
	Price             pgtype.Numeric `json:"price"`
	EstimatedDuration int32          `json:"estimated_duration"`
}

func (q *Queries) CreateBookingServiceSnapshot(ctx context.Context, arg CreateBookingServiceSnapshotParams) error {
	_, err := q.db.Exec(ctx, createBookingServiceSnapshot,
		arg.BookingID,
		arg.ServiceID,
		arg.ServiceTitle,
		arg.Price,
		arg.EstimatedDuration,
	)
	return err
}

const createParticipantServiceSnapshot = `-- name: CreateParticipantServiceSnapshot :exec
INSERT INTO booking_participant_services (booking_participant_id, service_id, service_title, price, estimated_duration)
VALUES ($1,$2,$3,$4,$5)
`

type CreateParticipantServiceSnapshotParams struct {
	BookingParticipantID int64          `json:"booking_participant_id"`
	ServiceID            int64          `json:"service_id"`
	ServiceTitle         string         `json:"service_title"`
	Price                pgtype.Numeric `json:"price"`
	EstimatedDuration    int32          `json:"estimated_duration"`
}

func (q *Queries) CreateParticipantServiceSnapshot(ctx context.Context, arg CreateParticipantServiceSnapshotParams) error {
	_, err := q.db.Exec(ctx, createParticipantServiceSnapshot,
		arg.BookingParticipantID,
		arg.ServiceID,
		arg.ServiceTitle,
		arg.Price,
		arg.EstimatedDuration,
	)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, booking_code, provider_id, customer_id, branch_id, staff_id, booking_type, booking_date, status, starts_at, ends_at,
  actual_started_at, actual_ended_at, total_duration, total_price, currency, customer_name, customer_phone,
  participant_count, notes, queue_number, checked_in_at, completed_at, held_at, hold_expires_at, expired_at,
  idempotency_key, created_at, updated_at
FROM bookings WHERE id = $1
`

type GetBookingByIDRow struct {
	ID               int64              `json:"id"`
	BookingCode      string             `json:"booking_code"`
	ProviderID       int64              `json:"provider_id"`
	CustomerID       pgtype.Int8        `json:"customer_id"`
	BranchID         pgtype.Int8        `json:"branch_id"`
	StaffID          pgtype.Int8        `json:"staff_id"`
	BookingType      string             `json:"booking_type"`
	BookingDate      pgtype.Date        `json:"booking_date"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	ActualStartedAt  pgtype.Timestamptz `json:"actual_started_at"`
	ActualEndedAt    pgtype.Timestamptz `json:"actual_ended_at"`
	TotalDuration    int32              `json:"total_duration"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	Currency         string             `json:"currency"`
	CustomerName     pgtype.Text        `json:"customer_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	ParticipantCount int16              `json:"participant_count"`
	Notes            pgtype.Text        `json:"notes"`
	QueueNumber      pgtype.Int4        `json:"queue_number"`
	CheckedInAt      pgtype.Timestamptz `json:"checked_in_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	HeldAt           pgtype.Timestamptz `json:"held_at"`
	HoldExpiresAt    pgtype.Timestamptz `json:"hold_expires_at"`
	ExpiredAt        pgtype.Timestamptz `json:"expired_at"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBookingByID(ctx context.Context, id int64) (GetBookingByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.ProviderID,
		&i.CustomerID,
		&i.BranchID,
		&i.StaffID,
		&i.BookingType,
		&i.BookingDate,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.ActualStartedAt,
		&i.ActualEndedAt,
		&i.TotalDuration,
		&i.TotalPrice,
		&i.Currency,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ParticipantCount,
		&i.Notes,
		&i.QueueNumber,
		&i.CheckedInAt,
		&i.CompletedAt,
		&i.HeldAt,
		&i.HoldExpiresAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedBookingByCode = `-- name: GetOwnedBookingByCode :one
SELECT id, booking_code, provider_id, customer_id, branch_id, staff_id, booking_type, booking_date, status, starts_at, ends_at,
  actual_started_at, actual_ended_at, total_duration, total_price, currency, customer_name, customer_phone,
  participant_count, notes, queue_number, checked_in_at, completed_at, held_at, hold_expires_at, expired_at,
  idempotency_key, created_at, updated_at
FROM bookings WHERE booking_code = $1 AND customer_id = $2
`

type GetOwnedBookingByCodeParams struct {
	BookingCode string      `json:"booking_code"`
	CustomerID  pgtype.Int8 `json:"customer_id"`
}

type GetOwnedBookingByCodeRow struct {
	ID               int64              `json:"id"`
	BookingCode      string             `json:"booking_code"`
	ProviderID       int64              `json:"provider_id"`
	CustomerID       pgtype.Int8        `json:"customer_id"`
	BranchID         pgtype.Int8        `json:"branch_id"`
	StaffID          pgtype.Int8        `json:"staff_id"`
	BookingType      string             `json:"booking_type"`
	BookingDate      pgtype.Date        `json:"booking_date"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	ActualStartedAt  pgtype.Timestamptz `json:"actual_started_at"`
	ActualEndedAt    pgtype.Timestamptz `json:"actual_ended_at"`
	TotalDuration    int32              `json:"total_duration"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	Currency         string             `json:"currency"`
	CustomerName     pgtype.Text        `json:"customer_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	ParticipantCount int16              `json:"participant_count"`
	Notes            pgtype.Text        `json:"notes"`
	QueueNumber      pgtype.Int4        `json:"queue_number"`
	CheckedInAt      pgtype.Timestamptz `json:"checked_in_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	HeldAt           pgtype.Timestamptz `json:"held_at"`
	HoldExpiresAt    pgtype.Timestamptz `json:"hold_expires_at"`
	ExpiredAt        pgtype.Timestamptz `json:"expired_at"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOwnedBookingByCode(ctx context.Context, arg GetOwnedBookingByCodeParams) (GetOwnedBookingByCodeRow, error) {
	row := q.db.QueryRow(ctx, getOwnedBookingByCode, arg.BookingCode, arg.CustomerID)
	var i GetOwnedBookingByCodeRow
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.ProviderID,
		&i.CustomerID,
		&i.BranchID,
		&i.StaffID,
		&i.BookingType,
		&i.BookingDate,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.ActualStartedAt,
		&i.ActualEndedAt,
		&i.TotalDuration,
		&i.TotalPrice,
		&i.Currency,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ParticipantCount,
		&i.Notes,
		&i.QueueNumber,
		&i.CheckedInAt,
		&i.CompletedAt,
		&i.HeldAt,
		&i.HoldExpiresAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBookingInbox = `-- name: InsertBookingInbox :execrows
INSERT INTO inbox_events (event_id, topic, partition_id, offset_id, event_type)
VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING
`

type InsertBookingInboxParams struct {
	EventID     pgtype.UUID `json:"event_id"`
	Topic       string      `json:"topic"`
	PartitionID int32       `json:"partition_id"`
	OffsetID    int64       `json:"offset_id"`
	EventType   string      `json:"event_type"`
}

func (q *Queries) InsertBookingInbox(ctx context.Context, arg InsertBookingInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBookingInbox,
		arg.EventID,
		arg.Topic,
		arg.PartitionID,
		arg.OffsetID,
		arg.EventType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBookingOutbox = `-- name: InsertBookingOutbox :exec
INSERT INTO outbox_events (id, aggregate_type, aggregate_id, event_type, event_version, payload, headers, occurred_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertBookingOutboxParams struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertBookingOutbox(ctx context.Context, arg InsertBookingOutboxParams) error {
	_, err := q.db.Exec(ctx, insertBookingOutbox,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.EventVersion,
		arg.Payload,
		arg.Headers,
		arg.OccurredAt,
	)
	return err
}

const listCustomerBookings = `-- name: ListCustomerBookings :many
SELECT id, booking_code, provider_id, customer_id, branch_id, staff_id, booking_type, booking_date, status, starts_at, ends_at,
  actual_started_at, actual_ended_at, total_duration, total_price, currency, customer_name, customer_phone,
  participant_count, notes, queue_number, checked_in_at, completed_at, held_at, hold_expires_at, expired_at,
  idempotency_key, created_at, updated_at
FROM bookings WHERE customer_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCustomerBookingsParams struct {
	CustomerID pgtype.Int8 `json:"customer_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListCustomerBookingsRow struct {
	ID               int64              `json:"id"`
	BookingCode      string             `json:"booking_code"`
	ProviderID       int64              `json:"provider_id"`
	CustomerID       pgtype.Int8        `json:"customer_id"`
	BranchID         pgtype.Int8        `json:"branch_id"`
	StaffID          pgtype.Int8        `json:"staff_id"`
	BookingType      string             `json:"booking_type"`
	BookingDate      pgtype.Date        `json:"booking_date"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	ActualStartedAt  pgtype.Timestamptz `json:"actual_started_at"`
	ActualEndedAt    pgtype.Timestamptz `json:"actual_ended_at"`
	TotalDuration    int32              `json:"total_duration"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	Currency         string             `json:"currency"`
	CustomerName     pgtype.Text        `json:"customer_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	ParticipantCount int16              `json:"participant_count"`
	Notes            pgtype.Text        `json:"notes"`
	QueueNumber      pgtype.Int4        `json:"queue_number"`
	CheckedInAt      pgtype.Timestamptz `json:"checked_in_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	HeldAt           pgtype.Timestamptz `json:"held_at"`
	HoldExpiresAt    pgtype.Timestamptz `json:"hold_expires_at"`
	ExpiredAt        pgtype.Timestamptz `json:"expired_at"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCustomerBookings(ctx context.Context, arg ListCustomerBookingsParams) ([]ListCustomerBookingsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerBookings, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerBookingsRow{}
	for rows.Next() {
		var i ListCustomerBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingCode,
			&i.ProviderID,
			&i.CustomerID,
			&i.BranchID,
			&i.StaffID,
			&i.BookingType,
			&i.BookingDate,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.ActualStartedAt,
			&i.ActualEndedAt,
			&i.TotalDuration,
			&i.TotalPrice,
			&i.Currency,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.ParticipantCount,
			&i.Notes,
			&i.QueueNumber,
			&i.CheckedInAt,
			&i.CompletedAt,
			&i.HeldAt,
			&i.HoldExpiresAt,
			&i.ExpiredAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBooking = `-- name: LockBooking :one
SELECT id, booking_code, provider_id, customer_id, branch_id, staff_id, booking_type, booking_date, status, starts_at, ends_at,
  actual_started_at, actual_ended_at, total_duration, total_price, currency, customer_name, customer_phone,
  participant_count, notes, queue_number, checked_in_at, completed_at, held_at, hold_expires_at, expired_at,
  idempotency_key, created_at, updated_at
FROM bookings WHERE id = $1 FOR UPDATE
`

type LockBookingRow struct {
	ID               int64              `json:"id"`
	BookingCode      string             `json:"booking_code"`
	ProviderID       int64              `json:"provider_id"`
	CustomerID       pgtype.Int8        `json:"customer_id"`
	BranchID         pgtype.Int8        `json:"branch_id"`
	StaffID          pgtype.Int8        `json:"staff_id"`
	BookingType      string             `json:"booking_type"`
	BookingDate      pgtype.Date        `json:"booking_date"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	ActualStartedAt  pgtype.Timestamptz `json:"actual_started_at"`
	ActualEndedAt    pgtype.Timestamptz `json:"actual_ended_at"`
	TotalDuration    int32              `json:"total_duration"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	Currency         string             `json:"currency"`
	CustomerName     pgtype.Text        `json:"customer_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	ParticipantCount int16              `json:"participant_count"`
	Notes            pgtype.Text        `json:"notes"`
	QueueNumber      pgtype.Int4        `json:"queue_number"`
	CheckedInAt      pgtype.Timestamptz `json:"checked_in_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	HeldAt           pgtype.Timestamptz `json:"held_at"`
	HoldExpiresAt    pgtype.Timestamptz `json:"hold_expires_at"`
	ExpiredAt        pgtype.Timestamptz `json:"expired_at"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LockBooking(ctx context.Context, id int64) (LockBookingRow, error) {
	row := q.db.QueryRow(ctx, lockBooking, id)
	var i LockBookingRow
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.ProviderID,
		&i.CustomerID,
		&i.BranchID,
		&i.StaffID,
		&i.BookingType,
		&i.BookingDate,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.ActualStartedAt,
		&i.ActualEndedAt,
		&i.TotalDuration,
		&i.TotalPrice,
		&i.Currency,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ParticipantCount,
		&i.Notes,
		&i.QueueNumber,
		&i.CheckedInAt,
		&i.CompletedAt,
		&i.HeldAt,
		&i.HoldExpiresAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockConflictingBookings = `-- name: LockConflictingBookings :many
SELECT id, starts_at, ends_at, status FROM bookings
WHERE staff_id = $1 AND starts_at < $3 AND ends_at > $2
  AND status IN ('pending','pending_hold','pending_payment','confirmed','waiting','checked_in','in_progress','inprogress')
FOR UPDATE
`

type LockConflictingBookingsParams struct {
	StaffID  pgtype.Int8        `json:"staff_id"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

type LockConflictingBookingsRow struct {
	ID       int64              `json:"id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
	Status   string             `json:"status"`
}

func (q *Queries) LockConflictingBookings(ctx context.Context, arg LockConflictingBookingsParams) ([]LockConflictingBookingsRow, error) {
	rows, err := q.db.Query(ctx, lockConflictingBookings, arg.StaffID, arg.EndsAt, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockConflictingBookingsRow{}
	for rows.Next() {
		var i LockConflictingBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingState = `-- name: UpdateBookingState :one
UPDATE bookings SET status = $2, held_at = $3, hold_expires_at = $4, expired_at = $5, updated_at = now()
WHERE id = $1
RETURNING id, booking_code, provider_id, customer_id, branch_id, staff_id, booking_type, booking_date, status, starts_at, ends_at,
  actual_started_at, actual_ended_at, total_duration, total_price, currency, customer_name, customer_phone,
  participant_count, notes, queue_number, checked_in_at, completed_at, held_at, hold_expires_at, expired_at,
  idempotency_key, created_at, updated_at
`

type UpdateBookingStateParams struct {
	ID            int64              `json:"id"`
	Status        string             `json:"status"`
	HeldAt        pgtype.Timestamptz `json:"held_at"`
	HoldExpiresAt pgtype.Timestamptz `json:"hold_expires_at"`
	ExpiredAt     pgtype.Timestamptz `json:"expired_at"`
}

type UpdateBookingStateRow struct {
	ID               int64              `json:"id"`
	BookingCode      string             `json:"booking_code"`
	ProviderID       int64              `json:"provider_id"`
	CustomerID       pgtype.Int8        `json:"customer_id"`
	BranchID         pgtype.Int8        `json:"branch_id"`
	StaffID          pgtype.Int8        `json:"staff_id"`
	BookingType      string             `json:"booking_type"`
	BookingDate      pgtype.Date        `json:"booking_date"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	ActualStartedAt  pgtype.Timestamptz `json:"actual_started_at"`
	ActualEndedAt    pgtype.Timestamptz `json:"actual_ended_at"`
	TotalDuration    int32              `json:"total_duration"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	Currency         string             `json:"currency"`
	CustomerName     pgtype.Text        `json:"customer_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	ParticipantCount int16              `json:"participant_count"`
	Notes            pgtype.Text        `json:"notes"`
	QueueNumber      pgtype.Int4        `json:"queue_number"`
	CheckedInAt      pgtype.Timestamptz `json:"checked_in_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	HeldAt           pgtype.Timestamptz `json:"held_at"`
	HoldExpiresAt    pgtype.Timestamptz `json:"hold_expires_at"`
	ExpiredAt        pgtype.Timestamptz `json:"expired_at"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBookingState(ctx context.Context, arg UpdateBookingStateParams) (UpdateBookingStateRow, error) {
	row := q.db.QueryRow(ctx, updateBookingState,
		arg.ID,
		arg.Status,
		arg.HeldAt,
		arg.HoldExpiresAt,
		arg.ExpiredAt,
	)
	var i UpdateBookingStateRow
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.ProviderID,
		&i.CustomerID,
		&i.BranchID,
		&i.StaffID,
		&i.BookingType,
		&i.BookingDate,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.ActualStartedAt,
		&i.ActualEndedAt,
		&i.TotalDuration,
		&i.TotalPrice,
		&i.Currency,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ParticipantCount,
		&i.Notes,
		&i.QueueNumber,
		&i.CheckedInAt,
		&i.CompletedAt,
		&i.HeldAt,
		&i.HoldExpiresAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
