// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID               int64              `json:"id"`
	BookingCode      string             `json:"booking_code"`
	ProviderID       int64              `json:"provider_id"`
	CustomerID       pgtype.Int8        `json:"customer_id"`
	BranchID         pgtype.Int8        `json:"branch_id"`
	StaffID          pgtype.Int8        `json:"staff_id"`
	BookingType      string             `json:"booking_type"`
	Status           string             `json:"status"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	ActualStartedAt  pgtype.Timestamptz `json:"actual_started_at"`
	ActualEndedAt    pgtype.Timestamptz `json:"actual_ended_at"`
	TotalDuration    int32              `json:"total_duration"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	Currency         string             `json:"currency"`
	CustomerName     pgtype.Text        `json:"customer_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	ParticipantCount int16              `json:"participant_count"`
	Notes            pgtype.Text        `json:"notes"`
	QueueNumber      pgtype.Int4        `json:"queue_number"`
	CheckedInAt      pgtype.Timestamptz `json:"checked_in_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	HeldAt           pgtype.Timestamptz `json:"held_at"`
	HoldExpiresAt    pgtype.Timestamptz `json:"hold_expires_at"`
	ExpiredAt        pgtype.Timestamptz `json:"expired_at"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	PaymentType      string             `json:"payment_type"`
	PaymentChannel   pgtype.Text        `json:"payment_channel"`
	PaymentAmount    pgtype.Numeric     `json:"payment_amount"`
	DpAmount         pgtype.Numeric     `json:"dp_amount"`
	BookingDate      pgtype.Date        `json:"booking_date"`
}

type BookingParticipant struct {
	ID              int64              `json:"id"`
	BookingID       int64              `json:"booking_id"`
	Position        int16              `json:"position"`
	IsPrimary       bool               `json:"is_primary"`
	Name            string             `json:"name"`
	Phone           pgtype.Text        `json:"phone"`
	Email           pgtype.Text        `json:"email"`
	Gender          pgtype.Text        `json:"gender"`
	AgeGroup        pgtype.Text        `json:"age_group"`
	Description     pgtype.Text        `json:"description"`
	ProviderStaffID pgtype.Int8        `json:"provider_staff_id"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	TotalDuration   int32              `json:"total_duration"`
	TotalPrice      pgtype.Numeric     `json:"total_price"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type BookingParticipantService struct {
	ID                   int64              `json:"id"`
	BookingParticipantID int64              `json:"booking_participant_id"`
	ServiceID            int64              `json:"service_id"`
	ServiceTitle         string             `json:"service_title"`
	Price                pgtype.Numeric     `json:"price"`
	EstimatedDuration    int32              `json:"estimated_duration"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type BookingService struct {
	ID                int64              `json:"id"`
	BookingID         int64              `json:"booking_id"`
	ServiceID         int64              `json:"service_id"`
	ServiceTitle      string             `json:"service_title"`
	Price             pgtype.Numeric     `json:"price"`
	EstimatedDuration int32              `json:"estimated_duration"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type BookingStaffSlot struct {
	ID            int64              `json:"id"`
	BookingID     int64              `json:"booking_id"`
	ParticipantID pgtype.Int8        `json:"participant_id"`
	SourceKey     string             `json:"source_key"`
	StaffID       int64              `json:"staff_id"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type IdempotencyRecord struct {
	ActorID        int64              `json:"actor_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	ResourceID     pgtype.Int8        `json:"resource_id"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ActorType      string             `json:"actor_type"`
}

type InboxEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Topic       string             `json:"topic"`
	PartitionID int32              `json:"partition_id"`
	OffsetID    int64              `json:"offset_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.UUID        `json:"locked_by"`
}

type PaymentProjection struct {
	PaymentID int64              `json:"payment_id"`
	BookingID int64              `json:"booking_id"`
	Status    string             `json:"status"`
	EventID   pgtype.UUID        `json:"event_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
