// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO chat_messages (chat_thread_id, sender_id, sender_role, body, attachment_object_id, attachment_name, attachment_mime, attachment_size)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, chat_thread_id, sender_id, sender_role, body, attachment_object_id, attachment_name, attachment_mime, attachment_size, created_at, updated_at
`

type CreateMessageParams struct {
	ChatThreadID       int64       `json:"chat_thread_id"`
	SenderID           pgtype.Int8 `json:"sender_id"`
	SenderRole         string      `json:"sender_role"`
	Body               string      `json:"body"`
	AttachmentObjectID pgtype.UUID `json:"attachment_object_id"`
	AttachmentName     pgtype.Text `json:"attachment_name"`
	AttachmentMime     pgtype.Text `json:"attachment_mime"`
	AttachmentSize     pgtype.Int4 `json:"attachment_size"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChatThreadID,
		arg.SenderID,
		arg.SenderRole,
		arg.Body,
		arg.AttachmentObjectID,
		arg.AttachmentName,
		arg.AttachmentMime,
		arg.AttachmentSize,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatThreadID,
		&i.SenderID,
		&i.SenderRole,
		&i.Body,
		&i.AttachmentObjectID,
		&i.AttachmentName,
		&i.AttachmentMime,
		&i.AttachmentSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO chat_threads (provider_id, provider_user_id, branch_user_id, customer_user_id, conversation_type,
  status, ticket_status, ticket_subject, ticket_body, opened_by_user_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, provider_id, provider_user_id, branch_user_id, customer_user_id, conversation_type, last_message_id,
  last_message_at, last_admin_read_at, last_provider_read_at, last_branch_read_at, last_customer_read_at,
  status, ticket_status, ticket_subject, ticket_body, ticket_rejection_reason, ticket_requested_at,
  ticket_reviewed_at, ticket_reviewed_by, opened_by_user_id, closed_by_user_id, closed_at, created_at, updated_at
`

type CreateThreadParams struct {
	ProviderID       int64       `json:"provider_id"`
	ProviderUserID   pgtype.Int8 `json:"provider_user_id"`
	BranchUserID     pgtype.Int8 `json:"branch_user_id"`
	CustomerUserID   pgtype.Int8 `json:"customer_user_id"`
	ConversationType string      `json:"conversation_type"`
	Status           string      `json:"status"`
	TicketStatus     string      `json:"ticket_status"`
	TicketSubject    pgtype.Text `json:"ticket_subject"`
	TicketBody       pgtype.Text `json:"ticket_body"`
	OpenedByUserID   pgtype.Int8 `json:"opened_by_user_id"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (ChatThread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.ProviderID,
		arg.ProviderUserID,
		arg.BranchUserID,
		arg.CustomerUserID,
		arg.ConversationType,
		arg.Status,
		arg.TicketStatus,
		arg.TicketSubject,
		arg.TicketBody,
		arg.OpenedByUserID,
	)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderUserID,
		&i.BranchUserID,
		&i.CustomerUserID,
		&i.ConversationType,
		&i.LastMessageID,
		&i.LastMessageAt,
		&i.LastAdminReadAt,
		&i.LastProviderReadAt,
		&i.LastBranchReadAt,
		&i.LastCustomerReadAt,
		&i.Status,
		&i.TicketStatus,
		&i.TicketSubject,
		&i.TicketBody,
		&i.TicketRejectionReason,
		&i.TicketRequestedAt,
		&i.TicketReviewedAt,
		&i.TicketReviewedBy,
		&i.OpenedByUserID,
		&i.ClosedByUserID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, provider_id, provider_user_id, branch_user_id, customer_user_id, conversation_type, last_message_id,
  last_message_at, last_admin_read_at, last_provider_read_at, last_branch_read_at, last_customer_read_at,
  status, ticket_status, ticket_subject, ticket_body, ticket_rejection_reason, ticket_requested_at,
  ticket_reviewed_at, ticket_reviewed_by, opened_by_user_id, closed_by_user_id, closed_at, created_at, updated_at
FROM chat_threads WHERE id=$1
`

func (q *Queries) GetThread(ctx context.Context, id int64) (ChatThread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderUserID,
		&i.BranchUserID,
		&i.CustomerUserID,
		&i.ConversationType,
		&i.LastMessageID,
		&i.LastMessageAt,
		&i.LastAdminReadAt,
		&i.LastProviderReadAt,
		&i.LastBranchReadAt,
		&i.LastCustomerReadAt,
		&i.Status,
		&i.TicketStatus,
		&i.TicketSubject,
		&i.TicketBody,
		&i.TicketRejectionReason,
		&i.TicketRequestedAt,
		&i.TicketReviewedAt,
		&i.TicketReviewedBy,
		&i.OpenedByUserID,
		&i.ClosedByUserID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, chat_thread_id, sender_id, sender_role, body, attachment_object_id, attachment_name, attachment_mime, attachment_size, created_at, updated_at
FROM chat_messages WHERE chat_thread_id=$1 ORDER BY id LIMIT $2 OFFSET $3
`

type ListMessagesParams struct {
	ChatThreadID int64 `json:"chat_thread_id"`
	Limit        int32 `json:"limit"`
	Offset       int32 `json:"offset"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ChatThreadID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatThreadID,
			&i.SenderID,
			&i.SenderRole,
			&i.Body,
			&i.AttachmentObjectID,
			&i.AttachmentName,
			&i.AttachmentMime,
			&i.AttachmentSize,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThreadLastMessage = `-- name: UpdateThreadLastMessage :exec
UPDATE chat_threads SET last_message_id=$2, last_message_at=$3, updated_at=now() WHERE id=$1
`

type UpdateThreadLastMessageParams struct {
	ID            int64              `json:"id"`
	LastMessageID pgtype.Int8        `json:"last_message_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) UpdateThreadLastMessage(ctx context.Context, arg UpdateThreadLastMessageParams) error {
	_, err := q.db.Exec(ctx, updateThreadLastMessage, arg.ID, arg.LastMessageID, arg.LastMessageAt)
	return err
}
