// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatMessage struct {
	ID                 int64              `json:"id"`
	ChatThreadID       int64              `json:"chat_thread_id"`
	SenderID           pgtype.Int8        `json:"sender_id"`
	SenderRole         string             `json:"sender_role"`
	Body               string             `json:"body"`
	AttachmentObjectID pgtype.UUID        `json:"attachment_object_id"`
	AttachmentName     pgtype.Text        `json:"attachment_name"`
	AttachmentMime     pgtype.Text        `json:"attachment_mime"`
	AttachmentSize     pgtype.Int4        `json:"attachment_size"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ChatThread struct {
	ID                    int64              `json:"id"`
	ProviderID            int64              `json:"provider_id"`
	ProviderUserID        pgtype.Int8        `json:"provider_user_id"`
	BranchUserID          pgtype.Int8        `json:"branch_user_id"`
	CustomerUserID        pgtype.Int8        `json:"customer_user_id"`
	ConversationType      string             `json:"conversation_type"`
	LastMessageID         pgtype.Int8        `json:"last_message_id"`
	LastMessageAt         pgtype.Timestamptz `json:"last_message_at"`
	LastAdminReadAt       pgtype.Timestamptz `json:"last_admin_read_at"`
	LastProviderReadAt    pgtype.Timestamptz `json:"last_provider_read_at"`
	LastBranchReadAt      pgtype.Timestamptz `json:"last_branch_read_at"`
	LastCustomerReadAt    pgtype.Timestamptz `json:"last_customer_read_at"`
	Status                string             `json:"status"`
	TicketStatus          string             `json:"ticket_status"`
	TicketSubject         pgtype.Text        `json:"ticket_subject"`
	TicketBody            pgtype.Text        `json:"ticket_body"`
	TicketRejectionReason pgtype.Text        `json:"ticket_rejection_reason"`
	TicketRequestedAt     pgtype.Timestamptz `json:"ticket_requested_at"`
	TicketReviewedAt      pgtype.Timestamptz `json:"ticket_reviewed_at"`
	TicketReviewedBy      pgtype.Int8        `json:"ticket_reviewed_by"`
	OpenedByUserID        pgtype.Int8        `json:"opened_by_user_id"`
	ClosedByUserID        pgtype.Int8        `json:"closed_by_user_id"`
	ClosedAt              pgtype.Timestamptz `json:"closed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type InboxEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Topic       string             `json:"topic"`
	PartitionID int32              `json:"partition_id"`
	OffsetID    int64              `json:"offset_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.UUID        `json:"locked_by"`
}
