-- +goose Up
CREATE TABLE coupon_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id BIGINT NOT NULL REFERENCES coupons(id) ON DELETE RESTRICT,
    redemption_key TEXT NOT NULL UNIQUE,
    request_hash TEXT NOT NULL,
    discount_minor BIGINT NOT NULL CHECK(discount_minor >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX coupon_redemptions_coupon_idx ON coupon_redemptions(coupon_id);

-- +goose Down
DROP TABLE IF EXISTS coupon_redemptions;
