-- +goose Up
CREATE TABLE service_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES service_categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    image_object_id UUID,
    icon TEXT,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    is_featured BOOLEAN NOT NULL DEFAULT true,
    sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK(parent_id IS NULL OR parent_id <> id)
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    category_text TEXT,
    category_id BIGINT REFERENCES service_categories(id) ON DELETE SET NULL,
    code TEXT,
    description TEXT,
    includes TEXT,
    price_type TEXT,
    price NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (price >= 0),
    minimum_duration INTEGER NOT NULL DEFAULT 0 CHECK (minimum_duration >= 0),
    estimated_duration INTEGER NOT NULL DEFAULT 30 CHECK (estimated_duration > 0),
    maximum_duration INTEGER NOT NULL DEFAULT 60 CHECK (maximum_duration > 0),
    is_queue_enabled BOOLEAN NOT NULL DEFAULT true,
    is_scheduled_enabled BOOLEAN NOT NULL DEFAULT true,
    requires_dp BOOLEAN NOT NULL DEFAULT false,
    dp_amount NUMERIC(12,2),
    payment_policy TEXT,
    slots JSONB,
    additional_services JSONB,
    holidays JSONB,
    branch_ids JSONB,
    gallery_object_ids JSONB,
    video_url TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    verify_status TEXT NOT NULL DEFAULT 'verified' CHECK (verify_status IN ('verified', 'pending', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(provider_id, slug),
    UNIQUE(provider_id, code),
    CHECK(maximum_duration >= estimated_duration AND estimated_duration >= minimum_duration),
    CHECK(dp_amount IS NULL OR dp_amount >= 0)
);
CREATE INDEX services_public_idx ON services(status, verify_status, category_id);
CREATE INDEX services_provider_idx ON services(provider_id, status);

CREATE TABLE coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    product_type TEXT NOT NULL DEFAULT 'all' CHECK (product_type IN ('all', 'service', 'category')),
    product_ids JSONB,
    coupon_type TEXT NOT NULL DEFAULT 'percentage' CHECK (coupon_type IN ('percentage', 'fixed')),
    coupon_value NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (coupon_value >= 0),
    quantity INTEGER CHECK (quantity IS NULL OR quantity >= 0),
    used_count INTEGER NOT NULL DEFAULT 0 CHECK (used_count >= 0),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK(end_date >= start_date),
    CHECK(coupon_type <> 'percentage' OR coupon_value <= 100)
);
CREATE INDEX coupons_active_dates_idx ON coupons(status, start_date, end_date);

CREATE TABLE provider_readiness_projection (
    provider_id BIGINT PRIMARY KEY,
    ready BOOLEAN NOT NULL DEFAULT false,
    active_branch_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE review_projection (
    review_id BIGINT PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    staff_id BIGINT,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL,
    event_type TEXT NOT NULL, event_version INTEGER NOT NULL, payload BYTEA NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ, attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX catalog_outbox_unpublished_idx ON outbox_events(occurred_at) WHERE published_at IS NULL;

CREATE TABLE inbox_events (
    event_id UUID PRIMARY KEY, topic TEXT NOT NULL, partition_id INTEGER NOT NULL,
    offset_id BIGINT NOT NULL, event_type TEXT NOT NULL, processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(topic, partition_id, offset_id)
);

-- +goose Down
DROP TABLE IF EXISTS inbox_events, outbox_events, review_projection, provider_readiness_projection, coupons, services, service_categories CASCADE;

