// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshSession = `-- name: CreateRefreshSession :exec
INSERT INTO refresh_sessions (id, user_id, family_id, token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateRefreshSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    int64              `json:"user_id"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	TokenHash []byte             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) error {
	_, err := q.db.Exec(ctx, createRefreshSession,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, username, email, password_hash, role, status, provider_id, branch_id, provider_role_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, username, email, email_verified_at, password_hash, role, status, provider_id, branch_id, provider_role_id, permissions, created_at, updated_at
`

type CreateUserParams struct {
	Name           string      `json:"name"`
	Username       pgtype.Text `json:"username"`
	Email          string      `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	Role           string      `json:"role"`
	Status         string      `json:"status"`
	ProviderID     pgtype.Int8 `json:"provider_id"`
	BranchID       pgtype.Int8 `json:"branch_id"`
	ProviderRoleID pgtype.Int8 `json:"provider_role_id"`
}

type CreateUserRow struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	Username        pgtype.Text        `json:"username"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	ProviderID      pgtype.Int8        `json:"provider_id"`
	BranchID        pgtype.Int8        `json:"branch_id"`
	ProviderRoleID  pgtype.Int8        `json:"provider_role_id"`
	Permissions     []string           `json:"permissions"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.ProviderID,
		arg.BranchID,
		arg.ProviderRoleID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ProviderID,
		&i.BranchID,
		&i.ProviderRoleID,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshSessionForUpdate = `-- name: GetRefreshSessionForUpdate :one
SELECT id, user_id, family_id, token_hash, user_agent, ip_address, expires_at, used_at, revoked_at, replaced_by, created_at
FROM refresh_sessions WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetRefreshSessionForUpdate(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionForUpdate, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, username, email, email_verified_at, password_hash, role, status, provider_id, branch_id, provider_role_id, permissions, created_at, updated_at
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	Username        pgtype.Text        `json:"username"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	ProviderID      pgtype.Int8        `json:"provider_id"`
	BranchID        pgtype.Int8        `json:"branch_id"`
	ProviderRoleID  pgtype.Int8        `json:"provider_role_id"`
	Permissions     []string           `json:"permissions"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ProviderID,
		&i.BranchID,
		&i.ProviderRoleID,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, username, email, email_verified_at, password_hash, role, status, provider_id, branch_id, provider_role_id, permissions, created_at, updated_at
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	Username        pgtype.Text        `json:"username"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	ProviderID      pgtype.Int8        `json:"provider_id"`
	BranchID        pgtype.Int8        `json:"branch_id"`
	ProviderRoleID  pgtype.Int8        `json:"provider_role_id"`
	Permissions     []string           `json:"permissions"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ProviderID,
		&i.BranchID,
		&i.ProviderRoleID,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIdentityOutbox = `-- name: InsertIdentityOutbox :exec
INSERT INTO outbox_events (id, aggregate_type, aggregate_id, event_type, event_version, payload, headers, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertIdentityOutboxParams struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertIdentityOutbox(ctx context.Context, arg InsertIdentityOutboxParams) error {
	_, err := q.db.Exec(ctx, insertIdentityOutbox,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.EventVersion,
		arg.Payload,
		arg.Headers,
		arg.OccurredAt,
	)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_sessions SET revoked_at = COALESCE(revoked_at, now()) WHERE family_id = $1
`

func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, familyID)
	return err
}

const rotateRefreshSession = `-- name: RotateRefreshSession :exec
UPDATE refresh_sessions SET used_at = now(), replaced_by = $2 WHERE id = $1 AND used_at IS NULL AND revoked_at IS NULL
`

type RotateRefreshSessionParams struct {
	ID         pgtype.UUID `json:"id"`
	ReplacedBy pgtype.UUID `json:"replaced_by"`
}

func (q *Queries) RotateRefreshSession(ctx context.Context, arg RotateRefreshSessionParams) error {
	_, err := q.db.Exec(ctx, rotateRefreshSession, arg.ID, arg.ReplacedBy)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE users SET status = $2, updated_at = now() WHERE id = $1
RETURNING id, name, username, email, email_verified_at, password_hash, role, status, provider_id, branch_id, provider_role_id, permissions, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

type UpdateAccountStatusRow struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	Username        pgtype.Text        `json:"username"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	ProviderID      pgtype.Int8        `json:"provider_id"`
	BranchID        pgtype.Int8        `json:"branch_id"`
	ProviderRoleID  pgtype.Int8        `json:"provider_role_id"`
	Permissions     []string           `json:"permissions"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (UpdateAccountStatusRow, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i UpdateAccountStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ProviderID,
		&i.BranchID,
		&i.ProviderRoleID,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}
