// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InboxEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Topic       string             `json:"topic"`
	PartitionID int32              `json:"partition_id"`
	OffsetID    int64              `json:"offset_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.UUID        `json:"locked_by"`
}

type Payment struct {
	ID             int64              `json:"id"`
	BookingID      pgtype.Int8        `json:"booking_id"`
	CustomerID     pgtype.Int8        `json:"customer_id"`
	PaymentType    string             `json:"payment_type"`
	Amount         pgtype.Numeric     `json:"amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	PaymentMethod  string             `json:"payment_method"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	ProviderID     pgtype.Int8        `json:"provider_id"`
	BranchID       pgtype.Int8        `json:"branch_id"`
}

type PaymentGatewayTransaction struct {
	ID                    int64              `json:"id"`
	PaymentID             int64              `json:"payment_id"`
	Gateway               string             `json:"gateway"`
	PaymentChannel        pgtype.Text        `json:"payment_channel"`
	ProviderOrderID       pgtype.Text        `json:"provider_order_id"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	ProviderStatus        pgtype.Text        `json:"provider_status"`
	FraudStatus           pgtype.Text        `json:"fraud_status"`
	PaymentCodeLabel      pgtype.Text        `json:"payment_code_label"`
	PaymentCode           pgtype.Text        `json:"payment_code"`
	BillerCode            pgtype.Text        `json:"biller_code"`
	QrUrl                 pgtype.Text        `json:"qr_url"`
	DeeplinkUrl           pgtype.Text        `json:"deeplink_url"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	RawResponse           []byte             `json:"raw_response"`
	RawNotification       []byte             `json:"raw_notification"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type WebhookNotification struct {
	NotificationHash      string             `json:"notification_hash"`
	ProviderOrderID       string             `json:"provider_order_id"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	TransactionStatus     string             `json:"transaction_status"`
	SignatureKeyHash      string             `json:"signature_key_hash"`
	ReceivedAt            pgtype.Timestamptz `json:"received_at"`
	ProcessedAt           pgtype.Timestamptz `json:"processed_at"`
	ResultStatus          pgtype.Text        `json:"result_status"`
	Failure               pgtype.Text        `json:"failure"`
}
