// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (booking_id, customer_id, payment_type, amount, currency, status, payment_method, idempotency_key)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, booking_id, customer_id, payment_type, amount, currency, status, payment_method, idempotency_key, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	BookingID      pgtype.Int8    `json:"booking_id"`
	CustomerID     pgtype.Int8    `json:"customer_id"`
	PaymentType    string         `json:"payment_type"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Status         string         `json:"status"`
	PaymentMethod  string         `json:"payment_method"`
	IdempotencyKey pgtype.Text    `json:"idempotency_key"`
}

type CreatePaymentRow struct {
	ID             int64              `json:"id"`
	BookingID      pgtype.Int8        `json:"booking_id"`
	CustomerID     pgtype.Int8        `json:"customer_id"`
	PaymentType    string             `json:"payment_type"`
	Amount         pgtype.Numeric     `json:"amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	PaymentMethod  string             `json:"payment_method"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BookingID,
		arg.CustomerID,
		arg.PaymentType,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.PaymentMethod,
		arg.IdempotencyKey,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.CustomerID,
		&i.PaymentType,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByGatewayOrderIDForUpdate = `-- name: GetPaymentByGatewayOrderIDForUpdate :one
SELECT p.id, p.booking_id, p.customer_id, p.payment_type, p.amount, p.currency, p.status, p.payment_method,
       p.idempotency_key, p.paid_at, p.created_at, p.updated_at
FROM payments p JOIN payment_gateway_transactions g ON g.payment_id = p.id
WHERE g.provider_order_id = $1 FOR UPDATE OF p
`

type GetPaymentByGatewayOrderIDForUpdateRow struct {
	ID             int64              `json:"id"`
	BookingID      pgtype.Int8        `json:"booking_id"`
	CustomerID     pgtype.Int8        `json:"customer_id"`
	PaymentType    string             `json:"payment_type"`
	Amount         pgtype.Numeric     `json:"amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	PaymentMethod  string             `json:"payment_method"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPaymentByGatewayOrderIDForUpdate(ctx context.Context, providerOrderID pgtype.Text) (GetPaymentByGatewayOrderIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByGatewayOrderIDForUpdate, providerOrderID)
	var i GetPaymentByGatewayOrderIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.CustomerID,
		&i.PaymentType,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, booking_id, customer_id, payment_type, amount, currency, status, payment_method, idempotency_key, paid_at, created_at, updated_at
FROM payments WHERE id = $1
`

type GetPaymentByIDRow struct {
	ID             int64              `json:"id"`
	BookingID      pgtype.Int8        `json:"booking_id"`
	CustomerID     pgtype.Int8        `json:"customer_id"`
	PaymentType    string             `json:"payment_type"`
	Amount         pgtype.Numeric     `json:"amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	PaymentMethod  string             `json:"payment_method"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (GetPaymentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.CustomerID,
		&i.PaymentType,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaymentOutbox = `-- name: InsertPaymentOutbox :exec
INSERT INTO outbox_events (id, aggregate_type, aggregate_id, event_type, event_version, payload, headers, occurred_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertPaymentOutboxParams struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertPaymentOutbox(ctx context.Context, arg InsertPaymentOutboxParams) error {
	_, err := q.db.Exec(ctx, insertPaymentOutbox,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.EventVersion,
		arg.Payload,
		arg.Headers,
		arg.OccurredAt,
	)
	return err
}

const insertWebhookNotification = `-- name: InsertWebhookNotification :execrows
INSERT INTO webhook_notifications (notification_hash, provider_order_id, provider_transaction_id, transaction_status, signature_key_hash)
VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING
`

type InsertWebhookNotificationParams struct {
	NotificationHash      string      `json:"notification_hash"`
	ProviderOrderID       string      `json:"provider_order_id"`
	ProviderTransactionID pgtype.Text `json:"provider_transaction_id"`
	TransactionStatus     string      `json:"transaction_status"`
	SignatureKeyHash      string      `json:"signature_key_hash"`
}

func (q *Queries) InsertWebhookNotification(ctx context.Context, arg InsertWebhookNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookNotification,
		arg.NotificationHash,
		arg.ProviderOrderID,
		arg.ProviderTransactionID,
		arg.TransactionStatus,
		arg.SignatureKeyHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE webhook_notifications SET processed_at=now(), result_status=$2, failure=$3 WHERE notification_hash=$1
`

type MarkWebhookProcessedParams struct {
	NotificationHash string      `json:"notification_hash"`
	ResultStatus     pgtype.Text `json:"result_status"`
	Failure          pgtype.Text `json:"failure"`
}

func (q *Queries) MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, arg.NotificationHash, arg.ResultStatus, arg.Failure)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments SET status = $2, paid_at = $3, updated_at = now() WHERE id = $1
RETURNING id, booking_id, customer_id, payment_type, amount, currency, status, payment_method, idempotency_key, paid_at, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     int64              `json:"id"`
	Status string             `json:"status"`
	PaidAt pgtype.Timestamptz `json:"paid_at"`
}

type UpdatePaymentStatusRow struct {
	ID             int64              `json:"id"`
	BookingID      pgtype.Int8        `json:"booking_id"`
	CustomerID     pgtype.Int8        `json:"customer_id"`
	PaymentType    string             `json:"payment_type"`
	Amount         pgtype.Numeric     `json:"amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	PaymentMethod  string             `json:"payment_method"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (UpdatePaymentStatusRow, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status, arg.PaidAt)
	var i UpdatePaymentStatusRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.CustomerID,
		&i.PaymentType,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGatewayTransaction = `-- name: UpsertGatewayTransaction :one
INSERT INTO payment_gateway_transactions (payment_id, gateway, payment_channel, provider_order_id, provider_transaction_id,
  provider_status, fraud_status, payment_code_label, payment_code, biller_code, qr_url, deeplink_url, expires_at,
  raw_response, raw_notification)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
ON CONFLICT (provider_order_id) DO UPDATE SET
  provider_transaction_id=EXCLUDED.provider_transaction_id, provider_status=EXCLUDED.provider_status,
  fraud_status=EXCLUDED.fraud_status, payment_channel=EXCLUDED.payment_channel,
  raw_notification=EXCLUDED.raw_notification, updated_at=now()
RETURNING id, payment_id, gateway, payment_channel, provider_order_id, provider_transaction_id, provider_status,
  fraud_status, payment_code_label, payment_code, biller_code, qr_url, deeplink_url, expires_at,
  raw_response, raw_notification, created_at, updated_at
`

type UpsertGatewayTransactionParams struct {
	PaymentID             int64              `json:"payment_id"`
	Gateway               string             `json:"gateway"`
	PaymentChannel        pgtype.Text        `json:"payment_channel"`
	ProviderOrderID       pgtype.Text        `json:"provider_order_id"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	ProviderStatus        pgtype.Text        `json:"provider_status"`
	FraudStatus           pgtype.Text        `json:"fraud_status"`
	PaymentCodeLabel      pgtype.Text        `json:"payment_code_label"`
	PaymentCode           pgtype.Text        `json:"payment_code"`
	BillerCode            pgtype.Text        `json:"biller_code"`
	QrUrl                 pgtype.Text        `json:"qr_url"`
	DeeplinkUrl           pgtype.Text        `json:"deeplink_url"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	RawResponse           []byte             `json:"raw_response"`
	RawNotification       []byte             `json:"raw_notification"`
}

func (q *Queries) UpsertGatewayTransaction(ctx context.Context, arg UpsertGatewayTransactionParams) (PaymentGatewayTransaction, error) {
	row := q.db.QueryRow(ctx, upsertGatewayTransaction,
		arg.PaymentID,
		arg.Gateway,
		arg.PaymentChannel,
		arg.ProviderOrderID,
		arg.ProviderTransactionID,
		arg.ProviderStatus,
		arg.FraudStatus,
		arg.PaymentCodeLabel,
		arg.PaymentCode,
		arg.BillerCode,
		arg.QrUrl,
		arg.DeeplinkUrl,
		arg.ExpiresAt,
		arg.RawResponse,
		arg.RawNotification,
	)
	var i PaymentGatewayTransaction
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Gateway,
		&i.PaymentChannel,
		&i.ProviderOrderID,
		&i.ProviderTransactionID,
		&i.ProviderStatus,
		&i.FraudStatus,
		&i.PaymentCodeLabel,
		&i.PaymentCode,
		&i.BillerCode,
		&i.QrUrl,
		&i.DeeplinkUrl,
		&i.ExpiresAt,
		&i.RawResponse,
		&i.RawNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
