-- +goose Up
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    customer_id BIGINT,
    payment_type TEXT NOT NULL CHECK (payment_type IN ('dp', 'full_payment', 'pay_at_salon', 'subscription')),
    amount NUMERIC(15,2) NOT NULL CHECK (amount >= 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'IDR',
    status TEXT NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'pending', 'paid', 'failed', 'refunded', 'expired', 'cancelled')),
    payment_method TEXT NOT NULL,
    idempotency_key TEXT,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(customer_id, idempotency_key)
);
CREATE INDEX payments_booking_idx ON payments(booking_id, created_at DESC);

CREATE TABLE payment_gateway_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    gateway TEXT NOT NULL DEFAULT 'midtrans',
    payment_channel TEXT,
    provider_order_id TEXT UNIQUE,
    provider_transaction_id TEXT,
    provider_status TEXT,
    fraud_status TEXT,
    payment_code_label TEXT,
    payment_code TEXT,
    biller_code TEXT,
    qr_url TEXT,
    deeplink_url TEXT,
    expires_at TIMESTAMPTZ,
    raw_response JSONB,
    raw_notification JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX gateway_transactions_payment_idx ON payment_gateway_transactions(payment_id, created_at DESC);

CREATE TABLE webhook_notifications (
    notification_hash CHAR(64) PRIMARY KEY,
    provider_order_id TEXT NOT NULL,
    provider_transaction_id TEXT,
    transaction_status TEXT NOT NULL,
    signature_key_hash CHAR(64) NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ,
    result_status TEXT,
    failure TEXT
);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL,
    event_type TEXT NOT NULL, event_version INTEGER NOT NULL, payload BYTEA NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ, attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX payment_outbox_unpublished_idx ON outbox_events(occurred_at) WHERE published_at IS NULL;

CREATE TABLE inbox_events (
    event_id UUID PRIMARY KEY, topic TEXT NOT NULL, partition_id INTEGER NOT NULL,
    offset_id BIGINT NOT NULL, event_type TEXT NOT NULL, processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(topic, partition_id, offset_id)
);

-- +goose Down
DROP TABLE IF EXISTS inbox_events, outbox_events, webhook_notifications, payment_gateway_transactions, payments CASCADE;

