// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveCouponForUpdate = `-- name: GetActiveCouponForUpdate :one
SELECT id, code, product_type, product_ids, coupon_type, coupon_value, quantity, used_count, start_date, end_date, status, created_at, updated_at
FROM coupons WHERE code = $1 AND status = 'active' AND CURRENT_DATE BETWEEN start_date AND end_date FOR UPDATE
`

func (q *Queries) GetActiveCouponForUpdate(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getActiveCouponForUpdate, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductType,
		&i.ProductIds,
		&i.CouponType,
		&i.CouponValue,
		&i.Quantity,
		&i.UsedCount,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceSnapshot = `-- name: GetServiceSnapshot :many
SELECT id, provider_id, title, price, estimated_duration, is_queue_enabled, is_scheduled_enabled, requires_dp, dp_amount
FROM services WHERE provider_id = $1 AND id = ANY($2::bigint[]) AND status = 'active' AND verify_status = 'verified'
ORDER BY id LIMIT 500
`

type GetServiceSnapshotParams struct {
	ProviderID int64   `json:"provider_id"`
	Column2    []int64 `json:"column_2"`
}

type GetServiceSnapshotRow struct {
	ID                 int64          `json:"id"`
	ProviderID         int64          `json:"provider_id"`
	Title              string         `json:"title"`
	Price              pgtype.Numeric `json:"price"`
	EstimatedDuration  int32          `json:"estimated_duration"`
	IsQueueEnabled     bool           `json:"is_queue_enabled"`
	IsScheduledEnabled bool           `json:"is_scheduled_enabled"`
	RequiresDp         bool           `json:"requires_dp"`
	DpAmount           pgtype.Numeric `json:"dp_amount"`
}

func (q *Queries) GetServiceSnapshot(ctx context.Context, arg GetServiceSnapshotParams) ([]GetServiceSnapshotRow, error) {
	rows, err := q.db.Query(ctx, getServiceSnapshot, arg.ProviderID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetServiceSnapshotRow{}
	for rows.Next() {
		var i GetServiceSnapshotRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Title,
			&i.Price,
			&i.EstimatedDuration,
			&i.IsQueueEnabled,
			&i.IsScheduledEnabled,
			&i.RequiresDp,
			&i.DpAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCouponUsage = `-- name: IncrementCouponUsage :exec
UPDATE coupons SET used_count = used_count + 1, updated_at = now()
WHERE id = $1 AND (quantity IS NULL OR used_count < quantity)
`

func (q *Queries) IncrementCouponUsage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementCouponUsage, id)
	return err
}

const listProviderServices = `-- name: ListProviderServices :many
SELECT id, provider_id, title, slug, category_text, category_id, code, description, includes, price_type, price,
       minimum_duration, estimated_duration, maximum_duration, is_queue_enabled, is_scheduled_enabled, requires_dp,
       dp_amount, payment_policy, slots, additional_services, holidays, branch_ids, gallery_object_ids, video_url,
       status, verify_status, created_at, updated_at
FROM services WHERE provider_id = $1 ORDER BY id LIMIT $2 OFFSET $3
`

type ListProviderServicesParams struct {
	ProviderID int64 `json:"provider_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListProviderServices(ctx context.Context, arg ListProviderServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listProviderServices, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Title,
			&i.Slug,
			&i.CategoryText,
			&i.CategoryID,
			&i.Code,
			&i.Description,
			&i.Includes,
			&i.PriceType,
			&i.Price,
			&i.MinimumDuration,
			&i.EstimatedDuration,
			&i.MaximumDuration,
			&i.IsQueueEnabled,
			&i.IsScheduledEnabled,
			&i.RequiresDp,
			&i.DpAmount,
			&i.PaymentPolicy,
			&i.Slots,
			&i.AdditionalServices,
			&i.Holidays,
			&i.BranchIds,
			&i.GalleryObjectIds,
			&i.VideoUrl,
			&i.Status,
			&i.VerifyStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCategories = `-- name: ListPublicCategories :many
SELECT id, parent_id, name, slug, image_object_id, icon, description, status, is_featured, sort_order, created_at, updated_at
FROM service_categories WHERE status = 'active' ORDER BY sort_order, name LIMIT $1 OFFSET $2
`

type ListPublicCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicCategories(ctx context.Context, arg ListPublicCategoriesParams) ([]ServiceCategory, error) {
	rows, err := q.db.Query(ctx, listPublicCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceCategory{}
	for rows.Next() {
		var i ServiceCategory
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.ImageObjectID,
			&i.Icon,
			&i.Description,
			&i.Status,
			&i.IsFeatured,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicServices = `-- name: ListPublicServices :many
SELECT id, provider_id, title, slug, category_text, category_id, code, description, includes, price_type, price,
       minimum_duration, estimated_duration, maximum_duration, is_queue_enabled, is_scheduled_enabled, requires_dp,
       dp_amount, payment_policy, slots, additional_services, holidays, branch_ids, gallery_object_ids, video_url,
       status, verify_status, created_at, updated_at
FROM services WHERE status = 'active' AND verify_status = 'verified' ORDER BY id LIMIT $1 OFFSET $2
`

type ListPublicServicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicServices(ctx context.Context, arg ListPublicServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listPublicServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Title,
			&i.Slug,
			&i.CategoryText,
			&i.CategoryID,
			&i.Code,
			&i.Description,
			&i.Includes,
			&i.PriceType,
			&i.Price,
			&i.MinimumDuration,
			&i.EstimatedDuration,
			&i.MaximumDuration,
			&i.IsQueueEnabled,
			&i.IsScheduledEnabled,
			&i.RequiresDp,
			&i.DpAmount,
			&i.PaymentPolicy,
			&i.Slots,
			&i.AdditionalServices,
			&i.Holidays,
			&i.BranchIds,
			&i.GalleryObjectIds,
			&i.VideoUrl,
			&i.Status,
			&i.VerifyStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
