// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BranchProjection struct {
	BranchID   int64              `json:"branch_id"`
	ProviderID int64              `json:"provider_id"`
	BranchName string             `json:"branch_name"`
	CityID     pgtype.Text        `json:"city_id"`
	StateID    pgtype.Text        `json:"state_id"`
	CountryID  pgtype.Text        `json:"country_id"`
	Address    pgtype.Text        `json:"address"`
	Latitude   pgtype.Numeric     `json:"latitude"`
	Longitude  pgtype.Numeric     `json:"longitude"`
	Status     string             `json:"status"`
	Ready      bool               `json:"ready"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Coupon struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	ProductType string             `json:"product_type"`
	ProductIds  []byte             `json:"product_ids"`
	CouponType  string             `json:"coupon_type"`
	CouponValue pgtype.Numeric     `json:"coupon_value"`
	Quantity    pgtype.Int4        `json:"quantity"`
	UsedCount   int32              `json:"used_count"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CouponRedemption struct {
	ID            int64              `json:"id"`
	CouponID      int64              `json:"coupon_id"`
	RedemptionKey string             `json:"redemption_key"`
	RequestHash   string             `json:"request_hash"`
	DiscountMinor int64              `json:"discount_minor"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type InboxEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Topic       string             `json:"topic"`
	PartitionID int32              `json:"partition_id"`
	OffsetID    int64              `json:"offset_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.UUID        `json:"locked_by"`
}

type ProviderProjection struct {
	ProviderID int64              `json:"provider_id"`
	Name       string             `json:"name"`
	Category   pgtype.Text        `json:"category"`
	Status     string             `json:"status"`
	Ready      bool               `json:"ready"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProviderReadinessProjection struct {
	ProviderID      int64              `json:"provider_id"`
	Ready           bool               `json:"ready"`
	ActiveBranchIds []byte             `json:"active_branch_ids"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ReviewProjection struct {
	ReviewID  int64              `json:"review_id"`
	BranchID  int64              `json:"branch_id"`
	StaffID   pgtype.Int8        `json:"staff_id"`
	Rating    int16              `json:"rating"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID                 int64              `json:"id"`
	ProviderID         int64              `json:"provider_id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	CategoryText       pgtype.Text        `json:"category_text"`
	CategoryID         pgtype.Int8        `json:"category_id"`
	Code               pgtype.Text        `json:"code"`
	Description        pgtype.Text        `json:"description"`
	Includes           pgtype.Text        `json:"includes"`
	PriceType          pgtype.Text        `json:"price_type"`
	Price              pgtype.Numeric     `json:"price"`
	MinimumDuration    int32              `json:"minimum_duration"`
	EstimatedDuration  int32              `json:"estimated_duration"`
	MaximumDuration    int32              `json:"maximum_duration"`
	IsQueueEnabled     bool               `json:"is_queue_enabled"`
	IsScheduledEnabled bool               `json:"is_scheduled_enabled"`
	RequiresDp         bool               `json:"requires_dp"`
	DpAmount           pgtype.Numeric     `json:"dp_amount"`
	PaymentPolicy      pgtype.Text        `json:"payment_policy"`
	Slots              []byte             `json:"slots"`
	AdditionalServices []byte             `json:"additional_services"`
	Holidays           []byte             `json:"holidays"`
	BranchIds          []byte             `json:"branch_ids"`
	GalleryObjectIds   []byte             `json:"gallery_object_ids"`
	VideoUrl           pgtype.Text        `json:"video_url"`
	Status             string             `json:"status"`
	VerifyStatus       string             `json:"verify_status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ServiceCategory struct {
	ID            int64              `json:"id"`
	ParentID      pgtype.Int8        `json:"parent_id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	ImageObjectID pgtype.UUID        `json:"image_object_id"`
	Icon          pgtype.Text        `json:"icon"`
	Description   pgtype.Text        `json:"description"`
	Status        string             `json:"status"`
	IsFeatured    bool               `json:"is_featured"`
	SortOrder     int32              `json:"sort_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type StaffProjection struct {
	StaffID     int64              `json:"staff_id"`
	ProviderID  int64              `json:"provider_id"`
	BranchID    pgtype.Int8        `json:"branch_id"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	ServiceIds  []byte             `json:"service_ids"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
