-- +goose Up
CREATE TABLE provider_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    image TEXT,
    phone_number TEXT,
    category TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    onboarding_status TEXT NOT NULL DEFAULT 'not_started' CHECK (onboarding_status IN ('not_started', 'in_progress', 'skipped', 'completed')),
    onboarding_current_step TEXT,
    onboarding_version INTEGER NOT NULL DEFAULT 1,
    trial_starts_at TIMESTAMPTZ,
    trial_ends_at TIMESTAMPTZ,
    document_status TEXT NOT NULL DEFAULT 'pending' CHECK (document_status IN ('pending', 'verified', 'rejected')),
    ktp_object_id UUID,
    nib_number VARCHAR(50),
    nib_object_id UUID,
    business_object_id UUID,
    document_note TEXT,
    document_submitted_at TIMESTAMPTZ,
    document_verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE provider_branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES provider_profiles(id) ON DELETE CASCADE,
    branch_name TEXT NOT NULL,
    email TEXT,
    phone_code TEXT NOT NULL DEFAULT '+1',
    phone_number TEXT,
    address TEXT,
    country_id TEXT,
    state_id TEXT,
    city_id TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    zip_code TEXT,
    working_start_hour TIME,
    working_end_hour TIME,
    working_days JSONB,
    holidays JSONB,
    image_object_id UUID,
    image_object_ids JSONB,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX provider_branches_provider_idx ON provider_branches(provider_id, status);

CREATE TABLE provider_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES provider_profiles(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES provider_branches(id) ON DELETE CASCADE,
    role_name TEXT NOT NULL,
    slug TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(provider_id, slug)
);

CREATE TABLE provider_role_menu_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_role_id BIGINT NOT NULL REFERENCES provider_roles(id) ON DELETE CASCADE,
    menu_key TEXT NOT NULL,
    UNIQUE(provider_role_id, menu_key)
);

CREATE TABLE provider_staffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES provider_profiles(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES provider_branches(id) ON DELETE SET NULL,
    provider_role_id BIGINT REFERENCES provider_roles(id) ON DELETE SET NULL,
    image_object_id UUID,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    username TEXT,
    country_code VARCHAR(20),
    phone_number TEXT,
    gender TEXT CHECK (gender IS NULL OR gender IN ('male', 'female', 'other')),
    date_of_birth DATE,
    address TEXT,
    country_id TEXT,
    state_id TEXT,
    city_id TEXT,
    postal_code TEXT,
    bio TEXT,
    category_id BIGINT,
    role TEXT NOT NULL DEFAULT 'staff',
    rating NUMERIC(3,2),
    current_status TEXT NOT NULL DEFAULT 'available' CHECK (current_status IN ('available', 'busy', 'offline')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(provider_id, email)
);
CREATE INDEX provider_staffs_scope_idx ON provider_staffs(provider_id, branch_id, status);

CREATE TABLE staff_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT NOT NULL REFERENCES provider_staffs(id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(staff_id, service_id)
);

CREATE TABLE staff_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT NOT NULL REFERENCES provider_staffs(id) ON DELETE CASCADE,
    day_of_week TEXT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK(start_time < end_time),
    UNIQUE(staff_id, day_of_week, start_time, end_time)
);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL,
    event_type TEXT NOT NULL, event_version INTEGER NOT NULL, payload BYTEA NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ, attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX provider_outbox_unpublished_idx ON outbox_events(occurred_at) WHERE published_at IS NULL;

CREATE TABLE inbox_events (
    event_id UUID PRIMARY KEY, topic TEXT NOT NULL, partition_id INTEGER NOT NULL,
    offset_id BIGINT NOT NULL, event_type TEXT NOT NULL, processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(topic, partition_id, offset_id)
);

-- +goose Down
DROP TABLE IF EXISTS inbox_events, outbox_events, staff_schedules, staff_skills, provider_staffs, provider_role_menu_permissions, provider_roles, provider_branches, provider_profiles CASCADE;

