// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeMediaObject = `-- name: CompleteMediaObject :one
UPDATE media_objects SET size_bytes=$2, checksum_sha256=$3, status='ready', completed_at=now() WHERE id=$1 AND status='pending'
RETURNING id, owner_type, owner_id, purpose, bucket, object_key, content_type, size_bytes, checksum_sha256,
  visibility, status, created_at, completed_at, deleted_at
`

type CompleteMediaObjectParams struct {
	ID             pgtype.UUID `json:"id"`
	SizeBytes      pgtype.Int8 `json:"size_bytes"`
	ChecksumSha256 pgtype.Text `json:"checksum_sha256"`
}

func (q *Queries) CompleteMediaObject(ctx context.Context, arg CompleteMediaObjectParams) (MediaObject, error) {
	row := q.db.QueryRow(ctx, completeMediaObject, arg.ID, arg.SizeBytes, arg.ChecksumSha256)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Purpose,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMediaObject = `-- name: CreateMediaObject :one
INSERT INTO media_objects (id, owner_type, owner_id, purpose, bucket, object_key, content_type, visibility, status)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, owner_type, owner_id, purpose, bucket, object_key, content_type, size_bytes, checksum_sha256,
  visibility, status, created_at, completed_at, deleted_at
`

type CreateMediaObjectParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerType   string      `json:"owner_type"`
	OwnerID     string      `json:"owner_id"`
	Purpose     string      `json:"purpose"`
	Bucket      string      `json:"bucket"`
	ObjectKey   string      `json:"object_key"`
	ContentType pgtype.Text `json:"content_type"`
	Visibility  string      `json:"visibility"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateMediaObject(ctx context.Context, arg CreateMediaObjectParams) (MediaObject, error) {
	row := q.db.QueryRow(ctx, createMediaObject,
		arg.ID,
		arg.OwnerType,
		arg.OwnerID,
		arg.Purpose,
		arg.Bucket,
		arg.ObjectKey,
		arg.ContentType,
		arg.Visibility,
		arg.Status,
	)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Purpose,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMediaObject = `-- name: DeleteMediaObject :exec
UPDATE media_objects SET status='deleted', deleted_at=now() WHERE id=$1 AND owner_type=$2 AND owner_id=$3
`

type DeleteMediaObjectParams struct {
	ID        pgtype.UUID `json:"id"`
	OwnerType string      `json:"owner_type"`
	OwnerID   string      `json:"owner_id"`
}

func (q *Queries) DeleteMediaObject(ctx context.Context, arg DeleteMediaObjectParams) error {
	_, err := q.db.Exec(ctx, deleteMediaObject, arg.ID, arg.OwnerType, arg.OwnerID)
	return err
}

const getMediaObject = `-- name: GetMediaObject :one
SELECT id, owner_type, owner_id, purpose, bucket, object_key, content_type, size_bytes, checksum_sha256,
  visibility, status, created_at, completed_at, deleted_at
FROM media_objects WHERE id=$1
`

func (q *Queries) GetMediaObject(ctx context.Context, id pgtype.UUID) (MediaObject, error) {
	row := q.db.QueryRow(ctx, getMediaObject, id)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Purpose,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertMigrationEntry = `-- name: UpsertMigrationEntry :one
INSERT INTO media_migration_entries (migration_key, scope, subject_type, subject_id, subject_field, source_disk,
  source_path, source_fingerprint, target_disk, target_path, target_fingerprint, status)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
ON CONFLICT (migration_key) DO UPDATE SET status=EXCLUDED.status, updated_at=now()
RETURNING id, migration_key, scope, subject_type, subject_id, subject_field, source_disk, source_path,
  source_fingerprint, target_object_id, target_disk, target_path, target_fingerprint, source_checksum,
  target_checksum, archive_disk, archive_path, archive_fingerprint, archive_checksum, status, copy_started_at,
  copied_at, verified_at, cutover_at, archive_verified_at, source_retired_at, source_restored_at,
  rolled_back_at, retirement_count, rollback_count, error_message, created_at, updated_at
`

type UpsertMigrationEntryParams struct {
	MigrationKey      string `json:"migration_key"`
	Scope             string `json:"scope"`
	SubjectType       string `json:"subject_type"`
	SubjectID         int64  `json:"subject_id"`
	SubjectField      string `json:"subject_field"`
	SourceDisk        string `json:"source_disk"`
	SourcePath        string `json:"source_path"`
	SourceFingerprint string `json:"source_fingerprint"`
	TargetDisk        string `json:"target_disk"`
	TargetPath        string `json:"target_path"`
	TargetFingerprint string `json:"target_fingerprint"`
	Status            string `json:"status"`
}

func (q *Queries) UpsertMigrationEntry(ctx context.Context, arg UpsertMigrationEntryParams) (MediaMigrationEntry, error) {
	row := q.db.QueryRow(ctx, upsertMigrationEntry,
		arg.MigrationKey,
		arg.Scope,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectField,
		arg.SourceDisk,
		arg.SourcePath,
		arg.SourceFingerprint,
		arg.TargetDisk,
		arg.TargetPath,
		arg.TargetFingerprint,
		arg.Status,
	)
	var i MediaMigrationEntry
	err := row.Scan(
		&i.ID,
		&i.MigrationKey,
		&i.Scope,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectField,
		&i.SourceDisk,
		&i.SourcePath,
		&i.SourceFingerprint,
		&i.TargetObjectID,
		&i.TargetDisk,
		&i.TargetPath,
		&i.TargetFingerprint,
		&i.SourceChecksum,
		&i.TargetChecksum,
		&i.ArchiveDisk,
		&i.ArchivePath,
		&i.ArchiveFingerprint,
		&i.ArchiveChecksum,
		&i.Status,
		&i.CopyStartedAt,
		&i.CopiedAt,
		&i.VerifiedAt,
		&i.CutoverAt,
		&i.ArchiveVerifiedAt,
		&i.SourceRetiredAt,
		&i.SourceRestoredAt,
		&i.RolledBackAt,
		&i.RetirementCount,
		&i.RollbackCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
