// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InboxEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Topic       string             `json:"topic"`
	PartitionID int32              `json:"partition_id"`
	OffsetID    int64              `json:"offset_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type MediaMigrationEntry struct {
	ID                 int64              `json:"id"`
	MigrationKey       string             `json:"migration_key"`
	Scope              string             `json:"scope"`
	SubjectType        string             `json:"subject_type"`
	SubjectID          int64              `json:"subject_id"`
	SubjectField       string             `json:"subject_field"`
	SourceDisk         string             `json:"source_disk"`
	SourcePath         string             `json:"source_path"`
	SourceFingerprint  string             `json:"source_fingerprint"`
	TargetObjectID     pgtype.UUID        `json:"target_object_id"`
	TargetDisk         string             `json:"target_disk"`
	TargetPath         string             `json:"target_path"`
	TargetFingerprint  string             `json:"target_fingerprint"`
	SourceChecksum     pgtype.Text        `json:"source_checksum"`
	TargetChecksum     pgtype.Text        `json:"target_checksum"`
	ArchiveDisk        pgtype.Text        `json:"archive_disk"`
	ArchivePath        pgtype.Text        `json:"archive_path"`
	ArchiveFingerprint pgtype.Text        `json:"archive_fingerprint"`
	ArchiveChecksum    pgtype.Text        `json:"archive_checksum"`
	Status             string             `json:"status"`
	CopyStartedAt      pgtype.Timestamptz `json:"copy_started_at"`
	CopiedAt           pgtype.Timestamptz `json:"copied_at"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	CutoverAt          pgtype.Timestamptz `json:"cutover_at"`
	ArchiveVerifiedAt  pgtype.Timestamptz `json:"archive_verified_at"`
	SourceRetiredAt    pgtype.Timestamptz `json:"source_retired_at"`
	SourceRestoredAt   pgtype.Timestamptz `json:"source_restored_at"`
	RolledBackAt       pgtype.Timestamptz `json:"rolled_back_at"`
	RetirementCount    int32              `json:"retirement_count"`
	RollbackCount      int32              `json:"rollback_count"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type MediaObject struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerType      string             `json:"owner_type"`
	OwnerID        string             `json:"owner_id"`
	Purpose        string             `json:"purpose"`
	Bucket         string             `json:"bucket"`
	ObjectKey      string             `json:"object_key"`
	ContentType    pgtype.Text        `json:"content_type"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	ChecksumSha256 pgtype.Text        `json:"checksum_sha256"`
	Visibility     string             `json:"visibility"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.UUID        `json:"locked_by"`
}
