-- +goose Up
CREATE TABLE subscription_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(15,2) NOT NULL CHECK (price >= 0),
    duration_days INTEGER NOT NULL CHECK (duration_days > 0),
    max_branches INTEGER NOT NULL DEFAULT 1 CHECK (max_branches > 0),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE provider_trials (
    provider_id BIGINT PRIMARY KEY,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    source TEXT NOT NULL DEFAULT 'legacy_provider_projection',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK(ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at)
);

CREATE TABLE provider_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    plan_id BIGINT REFERENCES subscription_plans(id) ON DELETE SET NULL,
    plan_name TEXT NOT NULL,
    price NUMERIC(15,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'IDR',
    duration_days INTEGER NOT NULL,
    max_branches INTEGER NOT NULL DEFAULT 1,
    payment_status TEXT NOT NULL DEFAULT 'pending',
    subscription_status TEXT NOT NULL DEFAULT 'inactive',
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    midtrans_order_id TEXT UNIQUE,
    midtrans_transaction_id TEXT,
    payment_channel TEXT,
    midtrans_transaction_status TEXT,
    fraud_status TEXT,
    payment_code_label TEXT,
    payment_code TEXT,
    biller_code TEXT,
    qr_url TEXT,
    deeplink_url TEXT,
    gateway_expires_at TIMESTAMPTZ,
    gateway_response JSONB,
    gateway_notification JSONB,
    superseded_at TIMESTAMPTZ,
    late_settlement_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX provider_subscriptions_current_idx ON provider_subscriptions(provider_id, subscription_status, ends_at DESC);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL,
    event_type TEXT NOT NULL, event_version INTEGER NOT NULL, payload BYTEA NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ, attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX billing_outbox_unpublished_idx ON outbox_events(occurred_at) WHERE published_at IS NULL;

CREATE TABLE inbox_events (
    event_id UUID PRIMARY KEY, topic TEXT NOT NULL, partition_id INTEGER NOT NULL,
    offset_id BIGINT NOT NULL, event_type TEXT NOT NULL, processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(topic, partition_id, offset_id)
);

-- +goose Down
DROP TABLE IF EXISTS inbox_events, outbox_events, provider_subscriptions, provider_trials, subscription_plans CASCADE;

