-- +goose Up
CREATE TABLE media_objects (
    id UUID PRIMARY KEY,
    owner_type TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    purpose TEXT NOT NULL,
    bucket TEXT NOT NULL,
    object_key TEXT NOT NULL UNIQUE,
    content_type TEXT,
    size_bytes BIGINT CHECK (size_bytes IS NULL OR size_bytes >= 0),
    checksum_sha256 CHAR(64),
    visibility TEXT NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'public')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'ready', 'deleted', 'quarantined')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX media_objects_owner_idx ON media_objects(owner_type, owner_id, purpose);

CREATE TABLE media_migration_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_key CHAR(64) NOT NULL UNIQUE,
    scope VARCHAR(50) NOT NULL,
    subject_type VARCHAR(50) NOT NULL,
    subject_id BIGINT NOT NULL,
    subject_field VARCHAR(64) NOT NULL,
    source_disk VARCHAR(100) NOT NULL,
    source_path TEXT NOT NULL,
    source_fingerprint CHAR(64) NOT NULL,
    target_object_id UUID REFERENCES media_objects(id) ON DELETE SET NULL,
    target_disk VARCHAR(100) NOT NULL,
    target_path TEXT NOT NULL,
    target_fingerprint CHAR(64) NOT NULL,
    source_checksum CHAR(64),
    target_checksum CHAR(64),
    archive_disk VARCHAR(100),
    archive_path TEXT,
    archive_fingerprint CHAR(64),
    archive_checksum CHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'planned',
    copy_started_at TIMESTAMPTZ,
    copied_at TIMESTAMPTZ,
    verified_at TIMESTAMPTZ,
    cutover_at TIMESTAMPTZ,
    archive_verified_at TIMESTAMPTZ,
    source_retired_at TIMESTAMPTZ,
    source_restored_at TIMESTAMPTZ,
    rolled_back_at TIMESTAMPTZ,
    retirement_count INTEGER NOT NULL DEFAULT 0,
    rollback_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE inbox_events (
    event_id UUID PRIMARY KEY, topic TEXT NOT NULL, partition_id INTEGER NOT NULL,
    offset_id BIGINT NOT NULL, event_type TEXT NOT NULL, processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(topic, partition_id, offset_id)
);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL,
    event_type TEXT NOT NULL, event_version INTEGER NOT NULL, payload BYTEA NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ, attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX media_outbox_unpublished_idx ON outbox_events(occurred_at) WHERE published_at IS NULL;

-- +goose Down
DROP TABLE IF EXISTS outbox_events, inbox_events, media_migration_entries, media_objects CASCADE;

