-- +goose Up
CREATE TABLE booking_staff_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    participant_id BIGINT REFERENCES booking_participants(id) ON DELETE CASCADE,
    source_key TEXT NOT NULL,
    staff_id BIGINT NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(booking_id, source_key),
    CHECK(ends_at > starts_at)
);

INSERT INTO booking_staff_slots(booking_id,participant_id,source_key,staff_id,starts_at,ends_at,active)
SELECT p.booking_id,p.id,'participant:'||p.id,p.provider_staff_id,p.starts_at,p.ends_at,
       b.status IN ('pending','pending_hold','pending_payment','confirmed','waiting','checked_in','in_progress','inprogress')
FROM booking_participants p
JOIN bookings b ON b.id=p.booking_id
WHERE p.provider_staff_id IS NOT NULL AND p.starts_at IS NOT NULL AND p.ends_at IS NOT NULL;

INSERT INTO booking_staff_slots(booking_id,source_key,staff_id,starts_at,ends_at,active)
SELECT b.id,'booking',b.staff_id,b.starts_at,b.ends_at,
       b.status IN ('pending','pending_hold','pending_payment','confirmed','waiting','checked_in','in_progress','inprogress')
FROM bookings b
WHERE b.staff_id IS NOT NULL AND b.starts_at IS NOT NULL AND b.ends_at IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM booking_staff_slots slot WHERE slot.booking_id=b.id
  );

ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_no_staff_overlap;
ALTER TABLE booking_staff_slots ADD CONSTRAINT booking_staff_slots_no_overlap
    EXCLUDE USING gist (
        staff_id WITH =,
        tstzrange(starts_at,ends_at,'[)') WITH &&
    ) WHERE (active);

CREATE INDEX booking_staff_slots_booking_idx ON booking_staff_slots(booking_id);
CREATE INDEX booking_staff_slots_lookup_idx ON booking_staff_slots(staff_id,starts_at,ends_at) WHERE active;

-- +goose StatementBegin
CREATE FUNCTION sync_booking_staff_slots() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE booking_staff_slots
       SET active=NEW.status IN ('pending','pending_hold','pending_payment','confirmed','waiting','checked_in','in_progress','inprogress'),
           staff_id=CASE WHEN source_key='booking' THEN NEW.staff_id ELSE staff_id END,
           starts_at=CASE WHEN source_key='booking' THEN NEW.starts_at ELSE starts_at END,
           ends_at=CASE WHEN source_key='booking' THEN NEW.ends_at ELSE ends_at END,
           updated_at=now()
     WHERE booking_id=NEW.id;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER bookings_sync_staff_slots
AFTER UPDATE OF status,staff_id,starts_at,ends_at ON bookings
FOR EACH ROW EXECUTE FUNCTION sync_booking_staff_slots();

-- +goose Down
DROP TRIGGER IF EXISTS bookings_sync_staff_slots ON bookings;
DROP FUNCTION IF EXISTS sync_booking_staff_slots();
DROP TABLE IF EXISTS booking_staff_slots;
ALTER TABLE bookings ADD CONSTRAINT bookings_no_staff_overlap
    EXCLUDE USING gist (
        staff_id WITH =,
        tstzrange(starts_at,ends_at,'[)') WITH &&
    ) WHERE (
        staff_id IS NOT NULL AND starts_at IS NOT NULL AND ends_at IS NOT NULL
        AND status IN ('pending','pending_hold','pending_payment','confirmed','waiting','checked_in','in_progress','inprogress')
    );
