-- +goose Up
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_code TEXT NOT NULL UNIQUE,
    provider_id BIGINT NOT NULL,
    customer_id BIGINT,
    branch_id BIGINT,
    staff_id BIGINT,
    booking_type TEXT NOT NULL DEFAULT 'scheduled' CHECK (booking_type IN ('scheduled', 'queue', 'walk_in', 'manual', 'group')),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','pending','pending_hold','expired_hold','payment_expired','inprogress','completed','order_completed','refund_completed','provider_cancelled','customer_cancelled','rescheduled','pending_payment','confirmed','waiting','checked_in','in_progress','cancelled','no_show')),
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    actual_started_at TIMESTAMPTZ,
    actual_ended_at TIMESTAMPTZ,
    total_duration INTEGER NOT NULL DEFAULT 0 CHECK (total_duration >= 0),
    total_price NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_price >= 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'IDR',
    customer_name TEXT,
    customer_phone TEXT,
    participant_count SMALLINT NOT NULL DEFAULT 1 CHECK (participant_count > 0),
    notes TEXT,
    queue_number INTEGER,
    checked_in_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    held_at TIMESTAMPTZ,
    hold_expires_at TIMESTAMPTZ,
    expired_at TIMESTAMPTZ,
    idempotency_key TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK(ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);
CREATE UNIQUE INDEX bookings_customer_idempotency_idx ON bookings(customer_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX bookings_customer_time_idx ON bookings(customer_id, created_at DESC);
CREATE INDEX bookings_provider_branch_time_idx ON bookings(provider_id, branch_id, starts_at);
ALTER TABLE bookings ADD CONSTRAINT bookings_no_staff_overlap
    EXCLUDE USING gist (
        staff_id WITH =,
        tstzrange(starts_at, ends_at, '[)') WITH &&
    ) WHERE (
        staff_id IS NOT NULL AND starts_at IS NOT NULL AND ends_at IS NOT NULL
        AND status IN ('pending','pending_hold','pending_payment','confirmed','waiting','checked_in','in_progress','inprogress')
    );

CREATE TABLE booking_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL,
    service_title TEXT NOT NULL,
    price NUMERIC(12,2) NOT NULL DEFAULT 0,
    estimated_duration INTEGER NOT NULL DEFAULT 30,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE booking_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    position SMALLINT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT false,
    name TEXT NOT NULL,
    phone VARCHAR(30),
    email TEXT,
    gender VARCHAR(20),
    age_group VARCHAR(20),
    description TEXT,
    provider_staff_id BIGINT,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    total_duration INTEGER NOT NULL DEFAULT 0,
    total_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(booking_id, position),
    CHECK(ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);

CREATE TABLE booking_participant_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_participant_id BIGINT NOT NULL REFERENCES booking_participants(id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL,
    service_title TEXT NOT NULL,
    price NUMERIC(12,2) NOT NULL DEFAULT 0,
    estimated_duration INTEGER NOT NULL DEFAULT 30,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE idempotency_records (
    customer_id BIGINT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    resource_id BIGINT,
    response_status INTEGER,
    response_body JSONB,
    locked_until TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(customer_id, idempotency_key)
);

CREATE TABLE payment_projection (
    payment_id BIGINT PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    event_id UUID NOT NULL UNIQUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL,
    event_type TEXT NOT NULL, event_version INTEGER NOT NULL, payload BYTEA NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ, attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX booking_outbox_unpublished_idx ON outbox_events(occurred_at) WHERE published_at IS NULL;

CREATE TABLE inbox_events (
    event_id UUID PRIMARY KEY, topic TEXT NOT NULL, partition_id INTEGER NOT NULL,
    offset_id BIGINT NOT NULL, event_type TEXT NOT NULL, processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(topic, partition_id, offset_id)
);

-- +goose Down
DROP TABLE IF EXISTS inbox_events, outbox_events, payment_projection, idempotency_records, booking_participant_services, booking_participants, booking_services, bookings CASCADE;

