-- +goose Up
CREATE TABLE audit_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID UNIQUE,
    actor_type TEXT,
    actor_id TEXT,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT,
    provider_id BIGINT,
    branch_id BIGINT,
    request_id VARCHAR(128),
    correlation_id VARCHAR(128),
    trace_id VARCHAR(64),
    ip INET,
    user_agent TEXT,
    before_state JSONB,
    after_state JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX audit_records_resource_idx ON audit_records(resource_type, resource_id, created_at DESC);
CREATE INDEX audit_records_actor_idx ON audit_records(actor_id, created_at DESC);
CREATE INDEX audit_records_provider_idx ON audit_records(provider_id, created_at DESC);

CREATE TABLE inbox_events (
    event_id UUID PRIMARY KEY, topic TEXT NOT NULL, partition_id INTEGER NOT NULL,
    offset_id BIGINT NOT NULL, event_type TEXT NOT NULL, processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(topic, partition_id, offset_id)
);

-- +goose Down
DROP TABLE IF EXISTS inbox_events, audit_records CASCADE;

