// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditRecord = `-- name: CreateAuditRecord :one
INSERT INTO audit_records (event_id, actor_type, actor_id, action, resource_type, resource_id, provider_id, branch_id,
  request_id, correlation_id, trace_id, ip, user_agent, before_state, after_state, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
RETURNING id, event_id, actor_type, actor_id, action, resource_type, resource_id, provider_id, branch_id,
  request_id, correlation_id, trace_id, ip, user_agent, before_state, after_state, created_at
`

type CreateAuditRecordParams struct {
	EventID       pgtype.UUID        `json:"event_id"`
	ActorType     pgtype.Text        `json:"actor_type"`
	ActorID       pgtype.Text        `json:"actor_id"`
	Action        string             `json:"action"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    pgtype.Text        `json:"resource_id"`
	ProviderID    pgtype.Int8        `json:"provider_id"`
	BranchID      pgtype.Int8        `json:"branch_id"`
	RequestID     pgtype.Text        `json:"request_id"`
	CorrelationID pgtype.Text        `json:"correlation_id"`
	TraceID       pgtype.Text        `json:"trace_id"`
	Ip            *netip.Addr        `json:"ip"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	BeforeState   []byte             `json:"before_state"`
	AfterState    []byte             `json:"after_state"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuditRecord(ctx context.Context, arg CreateAuditRecordParams) (AuditRecord, error) {
	row := q.db.QueryRow(ctx, createAuditRecord,
		arg.EventID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ProviderID,
		arg.BranchID,
		arg.RequestID,
		arg.CorrelationID,
		arg.TraceID,
		arg.Ip,
		arg.UserAgent,
		arg.BeforeState,
		arg.AfterState,
		arg.CreatedAt,
	)
	var i AuditRecord
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.ProviderID,
		&i.BranchID,
		&i.RequestID,
		&i.CorrelationID,
		&i.TraceID,
		&i.Ip,
		&i.UserAgent,
		&i.BeforeState,
		&i.AfterState,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditInbox = `-- name: InsertAuditInbox :execrows
INSERT INTO inbox_events (event_id, topic, partition_id, offset_id, event_type)
VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING
`

type InsertAuditInboxParams struct {
	EventID     pgtype.UUID `json:"event_id"`
	Topic       string      `json:"topic"`
	PartitionID int32       `json:"partition_id"`
	OffsetID    int64       `json:"offset_id"`
	EventType   string      `json:"event_type"`
}

func (q *Queries) InsertAuditInbox(ctx context.Context, arg InsertAuditInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAuditInbox,
		arg.EventID,
		arg.Topic,
		arg.PartitionID,
		arg.OffsetID,
		arg.EventType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuditRecords = `-- name: ListAuditRecords :many
SELECT id, event_id, actor_type, actor_id, action, resource_type, resource_id, provider_id, branch_id,
  request_id, correlation_id, trace_id, ip, user_agent, before_state, after_state, created_at
FROM audit_records
WHERE ($1::bigint IS NULL OR provider_id=$1) AND ($2::text IS NULL OR resource_type=$2)
ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListAuditRecordsParams struct {
	Column1 int64  `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListAuditRecords(ctx context.Context, arg ListAuditRecordsParams) ([]AuditRecord, error) {
	rows, err := q.db.Query(ctx, listAuditRecords,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditRecord{}
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProviderID,
			&i.BranchID,
			&i.RequestID,
			&i.CorrelationID,
			&i.TraceID,
			&i.Ip,
			&i.UserAgent,
			&i.BeforeState,
			&i.AfterState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
