// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditRecord struct {
	ID            int64              `json:"id"`
	EventID       pgtype.UUID        `json:"event_id"`
	ActorType     pgtype.Text        `json:"actor_type"`
	ActorID       pgtype.Text        `json:"actor_id"`
	Action        string             `json:"action"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    pgtype.Text        `json:"resource_id"`
	ProviderID    pgtype.Int8        `json:"provider_id"`
	BranchID      pgtype.Int8        `json:"branch_id"`
	RequestID     pgtype.Text        `json:"request_id"`
	CorrelationID pgtype.Text        `json:"correlation_id"`
	TraceID       pgtype.Text        `json:"trace_id"`
	Ip            *netip.Addr        `json:"ip"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	BeforeState   []byte             `json:"before_state"`
	AfterState    []byte             `json:"after_state"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type InboxEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Topic       string             `json:"topic"`
	PartitionID int32              `json:"partition_id"`
	OffsetID    int64              `json:"offset_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}
