// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryAttempt struct {
	ID                pgtype.UUID        `json:"id"`
	NotificationID    int64              `json:"notification_id"`
	Channel           string             `json:"channel"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	LastError         pgtype.Text        `json:"last_error"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type InboxEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Topic       string             `json:"topic"`
	PartitionID int32              `json:"partition_id"`
	OffsetID    int64              `json:"offset_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type Notification struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      pgtype.Text        `json:"body"`
	Url       pgtype.Text        `json:"url"`
	Data      []byte             `json:"data"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.UUID        `json:"locked_by"`
}

type ProviderRecipientProjection struct {
	ProviderID int64              `json:"provider_id"`
	UserID     int64              `json:"user_id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
