// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :exec
INSERT INTO delivery_attempts (id, notification_id, channel, status, attempt_count, next_attempt_at)
VALUES ($1,$2,$3,$4,$5,$6)
`

type CreateDeliveryAttemptParams struct {
	ID             pgtype.UUID        `json:"id"`
	NotificationID int64              `json:"notification_id"`
	Channel        string             `json:"channel"`
	Status         string             `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, createDeliveryAttempt,
		arg.ID,
		arg.NotificationID,
		arg.Channel,
		arg.Status,
		arg.AttemptCount,
		arg.NextAttemptAt,
	)
	return err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, url, data)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, user_id, type, title, body, url, data, read_at, created_at, updated_at
`

type CreateNotificationParams struct {
	UserID int64       `json:"user_id"`
	Type   string      `json:"type"`
	Title  string      `json:"title"`
	Body   pgtype.Text `json:"body"`
	Url    pgtype.Text `json:"url"`
	Data   []byte      `json:"data"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.Data,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotificationInbox = `-- name: InsertNotificationInbox :execrows
INSERT INTO inbox_events (event_id, topic, partition_id, offset_id, event_type)
VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING
`

type InsertNotificationInboxParams struct {
	EventID     pgtype.UUID `json:"event_id"`
	Topic       string      `json:"topic"`
	PartitionID int32       `json:"partition_id"`
	OffsetID    int64       `json:"offset_id"`
	EventType   string      `json:"event_type"`
}

func (q *Queries) InsertNotificationInbox(ctx context.Context, arg InsertNotificationInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotificationInbox,
		arg.EventID,
		arg.Topic,
		arg.PartitionID,
		arg.OffsetID,
		arg.EventType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDueDeliveryAttempts = `-- name: ListDueDeliveryAttempts :many
SELECT id, notification_id, channel, status, attempt_count, next_attempt_at, last_error, provider_message_id, created_at, updated_at
FROM delivery_attempts WHERE status='pending' AND next_attempt_at<=now() ORDER BY next_attempt_at LIMIT $1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListDueDeliveryAttempts(ctx context.Context, limit int32) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDueDeliveryAttempts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryAttempt{}
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastError,
			&i.ProviderMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, body, url, data, read_at, created_at, updated_at
FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Url,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read_at=COALESCE(read_at,now()), updated_at=now() WHERE id=$1 AND user_id=$2
`

type MarkNotificationReadParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
