// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO provider_subscriptions (provider_id, plan_id, plan_name, price, currency, duration_days, max_branches, payment_status, subscription_status, midtrans_order_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, provider_id, plan_id, plan_name, price, currency, duration_days, max_branches, payment_status,
          subscription_status, starts_at, ends_at, midtrans_order_id, midtrans_transaction_id, payment_channel,
          midtrans_transaction_status, fraud_status, payment_code_label, payment_code, biller_code, qr_url,
          deeplink_url, gateway_expires_at, gateway_response, gateway_notification, superseded_at,
          late_settlement_at, paid_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ProviderID         int64          `json:"provider_id"`
	PlanID             pgtype.Int8    `json:"plan_id"`
	PlanName           string         `json:"plan_name"`
	Price              pgtype.Numeric `json:"price"`
	Currency           string         `json:"currency"`
	DurationDays       int32          `json:"duration_days"`
	MaxBranches        int32          `json:"max_branches"`
	PaymentStatus      string         `json:"payment_status"`
	SubscriptionStatus string         `json:"subscription_status"`
	MidtransOrderID    pgtype.Text    `json:"midtrans_order_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (ProviderSubscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ProviderID,
		arg.PlanID,
		arg.PlanName,
		arg.Price,
		arg.Currency,
		arg.DurationDays,
		arg.MaxBranches,
		arg.PaymentStatus,
		arg.SubscriptionStatus,
		arg.MidtransOrderID,
	)
	var i ProviderSubscription
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.PlanID,
		&i.PlanName,
		&i.Price,
		&i.Currency,
		&i.DurationDays,
		&i.MaxBranches,
		&i.PaymentStatus,
		&i.SubscriptionStatus,
		&i.StartsAt,
		&i.EndsAt,
		&i.MidtransOrderID,
		&i.MidtransTransactionID,
		&i.PaymentChannel,
		&i.MidtransTransactionStatus,
		&i.FraudStatus,
		&i.PaymentCodeLabel,
		&i.PaymentCode,
		&i.BillerCode,
		&i.QrUrl,
		&i.DeeplinkUrl,
		&i.GatewayExpiresAt,
		&i.GatewayResponse,
		&i.GatewayNotification,
		&i.SupersededAt,
		&i.LateSettlementAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentSubscription = `-- name: GetCurrentSubscription :one
SELECT id, provider_id, plan_id, plan_name, price, currency, duration_days, max_branches, payment_status,
       subscription_status, starts_at, ends_at, midtrans_order_id, midtrans_transaction_id, payment_channel,
       midtrans_transaction_status, fraud_status, payment_code_label, payment_code, biller_code, qr_url,
       deeplink_url, gateway_expires_at, gateway_response, gateway_notification, superseded_at,
       late_settlement_at, paid_at, created_at, updated_at
FROM provider_subscriptions
WHERE provider_id = $1 AND subscription_status = 'active' AND (ends_at IS NULL OR ends_at > now())
ORDER BY ends_at DESC NULLS FIRST LIMIT 1
`

func (q *Queries) GetCurrentSubscription(ctx context.Context, providerID int64) (ProviderSubscription, error) {
	row := q.db.QueryRow(ctx, getCurrentSubscription, providerID)
	var i ProviderSubscription
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.PlanID,
		&i.PlanName,
		&i.Price,
		&i.Currency,
		&i.DurationDays,
		&i.MaxBranches,
		&i.PaymentStatus,
		&i.SubscriptionStatus,
		&i.StartsAt,
		&i.EndsAt,
		&i.MidtransOrderID,
		&i.MidtransTransactionID,
		&i.PaymentChannel,
		&i.MidtransTransactionStatus,
		&i.FraudStatus,
		&i.PaymentCodeLabel,
		&i.PaymentCode,
		&i.BillerCode,
		&i.QrUrl,
		&i.DeeplinkUrl,
		&i.GatewayExpiresAt,
		&i.GatewayResponse,
		&i.GatewayNotification,
		&i.SupersededAt,
		&i.LateSettlementAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderTrial = `-- name: GetProviderTrial :one
SELECT provider_id, starts_at, ends_at, source, updated_at FROM provider_trials WHERE provider_id = $1
`

func (q *Queries) GetProviderTrial(ctx context.Context, providerID int64) (ProviderTrial, error) {
	row := q.db.QueryRow(ctx, getProviderTrial, providerID)
	var i ProviderTrial
	err := row.Scan(
		&i.ProviderID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, name, description, price, duration_days, max_branches, is_active, created_at, updated_at
FROM subscription_plans WHERE is_active = true ORDER BY price, id LIMIT 100
`

func (q *Queries) ListActivePlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPlan{}
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.DurationDays,
			&i.MaxBranches,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
