// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InboxEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Topic       string             `json:"topic"`
	PartitionID int32              `json:"partition_id"`
	OffsetID    int64              `json:"offset_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.UUID        `json:"locked_by"`
}

type ProviderSubscription struct {
	ID                        int64              `json:"id"`
	ProviderID                int64              `json:"provider_id"`
	PlanID                    pgtype.Int8        `json:"plan_id"`
	PlanName                  string             `json:"plan_name"`
	Price                     pgtype.Numeric     `json:"price"`
	Currency                  string             `json:"currency"`
	DurationDays              int32              `json:"duration_days"`
	MaxBranches               int32              `json:"max_branches"`
	PaymentStatus             string             `json:"payment_status"`
	SubscriptionStatus        string             `json:"subscription_status"`
	StartsAt                  pgtype.Timestamptz `json:"starts_at"`
	EndsAt                    pgtype.Timestamptz `json:"ends_at"`
	MidtransOrderID           pgtype.Text        `json:"midtrans_order_id"`
	MidtransTransactionID     pgtype.Text        `json:"midtrans_transaction_id"`
	PaymentChannel            pgtype.Text        `json:"payment_channel"`
	MidtransTransactionStatus pgtype.Text        `json:"midtrans_transaction_status"`
	FraudStatus               pgtype.Text        `json:"fraud_status"`
	PaymentCodeLabel          pgtype.Text        `json:"payment_code_label"`
	PaymentCode               pgtype.Text        `json:"payment_code"`
	BillerCode                pgtype.Text        `json:"biller_code"`
	QrUrl                     pgtype.Text        `json:"qr_url"`
	DeeplinkUrl               pgtype.Text        `json:"deeplink_url"`
	GatewayExpiresAt          pgtype.Timestamptz `json:"gateway_expires_at"`
	GatewayResponse           []byte             `json:"gateway_response"`
	GatewayNotification       []byte             `json:"gateway_notification"`
	SupersededAt              pgtype.Timestamptz `json:"superseded_at"`
	LateSettlementAt          pgtype.Timestamptz `json:"late_settlement_at"`
	PaidAt                    pgtype.Timestamptz `json:"paid_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type ProviderTrial struct {
	ProviderID int64              `json:"provider_id"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	EndsAt     pgtype.Timestamptz `json:"ends_at"`
	Source     string             `json:"source"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SubscriptionPlan struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Price        pgtype.Numeric     `json:"price"`
	DurationDays int32              `json:"duration_days"`
	MaxBranches  int32              `json:"max_branches"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
